# TODO: all data contained in this file should eventually be generated by the linker

.include "macros.inc"

.section _extab, "wa"  # 0x800054C0 - 0x80005B80
	# ROM: 0x10B780
glabel extab_0
	.4byte 0x58080000
	.4byte 0
glabel extab_1
	.4byte 0x10080000
	.4byte 0
glabel extab_2
	.4byte 0x10080000
	.4byte 0
glabel extab_3
	.4byte 0x20080000
	.4byte 0
glabel extab_4
	.4byte 0x18080000
	.4byte 0
glabel extab_5
	.4byte 0x30080000
	.4byte 0
glabel extab_6
	.4byte 0x28080000
	.4byte 0
glabel extab_7
	.4byte 0x40080000
	.4byte 0
glabel extab_8
	.4byte 0x08080000
	.4byte 0
glabel extab_9
	.4byte 0x18080000
	.4byte 0
glabel extab_10
	.4byte 0x30080000
	.4byte 0
glabel extab_11
	.4byte 0x58080000
	.4byte 0
glabel extab_12
	.4byte 0x00080000
	.4byte 0
glabel extab_13
	.4byte 0x70080000
	.4byte 0
glabel extab_14
	.4byte 0x90080000
	.4byte 0
glabel extab_15
	.4byte 0x88080000
	.4byte 0
glabel extab_16
	.4byte 0x70080000
	.4byte 0
glabel extab_17
	.4byte 0x28080000
	.4byte 0
glabel extab_18
	.4byte 0x20C80000
	.4byte 0
glabel extab_19
	.4byte 0x20080000
	.4byte 0
glabel extab_20
	.4byte 0x08080000
	.4byte 0
glabel extab_21
	.4byte 0x08080000
	.4byte 0
glabel extab_22
	.4byte 0x00080000
	.4byte 0
glabel extab_23
	.4byte 0x20080000
	.4byte 0
glabel extab_24
	.4byte 0x00080000
	.4byte 0
glabel extab_25
	.4byte 0x60480000
	.4byte 0
glabel extab_26
	.4byte 0x48080000
	.4byte 0
glabel extab_27
	.4byte 0x20080000
	.4byte 0
glabel extab_28
	.4byte 0x20080000
	.4byte 0
glabel extab_29
	.4byte 0x10080000
	.4byte 0
glabel extab_30
	.4byte 0x10080000
	.4byte 0
glabel extab_31
	.4byte 0x31080000
	.4byte 0
glabel extab_32
	.4byte 0x00080000
	.4byte 0
glabel extab_33
	.4byte 0x90080000
	.4byte 0
glabel extab_34
	.4byte 0x10080000
	.4byte 0
glabel extab_35
	.4byte 0x08080000
	.4byte 0
glabel extab_36
	.4byte 0x18080000
	.4byte 0
glabel extab_37
	.4byte 0x20080000
	.4byte 0
glabel extab_38
	.4byte 0x18080000
	.4byte 0
glabel extab_39
	.4byte 0x18080000
	.4byte 0
glabel extab_40
	.4byte 0x08080000
	.4byte 0
glabel extab_41
	.4byte 0x28080000
	.4byte 0
glabel extab_42
	.4byte 0x08080000
	.4byte 0
glabel extab_43
	.4byte 0x18080000
	.4byte 0
glabel extab_44
	.4byte 0x20080000
	.4byte 0
glabel extab_45
	.4byte 0x00080000
	.4byte 0
glabel extab_46
	.4byte 0x50080000
	.4byte 0
glabel extab_47
	.4byte 0x18080000
	.4byte 0
glabel extab_48
	.4byte 0x28080000
	.4byte 0
glabel extab_49
	.4byte 0x00080000
	.4byte 0
glabel extab_50
	.4byte 0x00080000
	.4byte 0
glabel extab_51
	.4byte 0x40C80000
	.4byte 0
glabel extab_52
	.4byte 0x08080000
	.4byte 0
glabel extab_53
	.4byte 0x90080000
	.4byte 0
glabel extab_54
	.4byte 0x30080000
	.4byte 0
glabel extab_55
	.4byte 0x28080000
	.4byte 0
glabel extab_56
	.4byte 0x28080000
	.4byte 0
glabel extab_57
	.4byte 0x18080000
	.4byte 0
glabel extab_58
	.4byte 0x10080000
	.4byte 0
glabel extab_59
	.4byte 0x20080000
	.4byte 0
glabel extab_60
	.4byte 0x10080000
	.4byte 0
glabel extab_61
	.4byte 0x20080000
	.4byte 0
glabel extab_62
	.4byte 0x10080000
	.4byte 0
glabel extab_63
	.4byte 0x28080000
	.4byte 0
glabel extab_64
	.4byte 0x18080000
	.4byte 0
glabel extab_65
	.4byte 0x08080000
	.4byte 0
glabel extab_66
	.4byte 0x28080000
	.4byte 0
glabel extab_67
	.4byte 0x20080000
	.4byte 0
glabel extab_68
	.4byte 0x08080000
	.4byte 0
glabel extab_69
	.4byte 0x18080000
	.4byte 0
glabel extab_70
	.4byte 0x10080000
	.4byte 0
glabel extab_71
	.4byte 0x00080000
	.4byte 0
glabel extab_72
	.4byte 0x28080000
	.4byte 0
glabel extab_73
	.4byte 0x00080000
	.4byte 0
glabel extab_74
	.4byte 0x00080000
	.4byte 0
glabel extab_75
	.4byte 0x08080000
	.4byte 0
glabel extab_76
	.4byte 0x20080000
	.4byte 0
glabel extab_77
	.4byte 0x00080000
	.4byte 0
glabel extab_78
	.4byte 0x20080000
	.4byte 0
glabel extab_79
	.4byte 0x18080000
	.4byte 0
glabel extab_80
	.4byte 0x10080000
	.4byte 0
glabel extab_81
	.4byte 0x20080000
	.4byte 0
glabel extab_82
	.4byte 0x10080000
	.4byte 0
glabel extab_83
	.4byte 0x10080000
	.4byte 0
glabel extab_84
	.4byte 0x30080000
	.4byte 0
glabel extab_85
	.4byte 0x28080000
	.4byte 0
glabel extab_86
	.4byte 0x08080000
	.4byte 0
glabel extab_87
	.4byte 0x28080000
	.4byte 0
glabel extab_88
	.4byte 0x28080000
	.4byte 0
glabel extab_89
	.4byte 0x10080000
	.4byte 0
glabel extab_90
	.4byte 0x10080000
	.4byte 0
glabel extab_91
	.4byte 0x00080000
	.4byte 0
glabel extab_92
	.4byte 0x00080000
	.4byte 0
glabel extab_93
	.4byte 0x00080000
	.4byte 0
glabel extab_94
	.4byte 0x28080000
	.4byte 0
glabel extab_95
	.4byte 0x28080000
	.4byte 0
glabel extab_96
	.4byte 0x30080000
	.4byte 0
glabel extab_97
	.4byte 0x90C80000
	.4byte 0
glabel extab_98
	.4byte 0x30080000
	.4byte 0
glabel extab_99
	.4byte 0x08080000
	.4byte 0
glabel extab_100
	.4byte 0x08080000
	.4byte 0
glabel extab_101
	.4byte 0x08080000
	.4byte 0
glabel extab_102
	.4byte 0x08080000
	.4byte 0
glabel extab_103
	.4byte 0x08080000
	.4byte 0
glabel extab_104
	.4byte 0x90080000
	.4byte 0
glabel extab_105
	.4byte 0x08080000
	.4byte 0
glabel extab_106
	.4byte 0x30080000
	.4byte 0
glabel extab_107
	.4byte 0x08080000
	.4byte 0
glabel extab_109
	.4byte 0x18080000
	.4byte 0
glabel extab_110
	.4byte 0x10080000
	.4byte 0
glabel extab_111
	.4byte 0x10080000
	.4byte 0
glabel extab_112
	.4byte 0x20080000
	.4byte 0
glabel extab_113
	.4byte 0x28080000
	.4byte 0
glabel extab_114
	.4byte 0x00080000
	.4byte 0
glabel extab_115
	.4byte 0x00080000
	.4byte 0
glabel extab_116
	.4byte 0x00080000
	.4byte 0
glabel extab_117
	.4byte 0x08080000
	.4byte 0
glabel extab_118
	.4byte 0x00080000
	.4byte 0
glabel extab_119
	.4byte 0x00080000
	.4byte 0
glabel extab_120
	.4byte 0x20080000
	.4byte 0
glabel extab_121
	.4byte 0x00080000
	.4byte 0
glabel extab_122
	.4byte 0x28080000
	.4byte 0
glabel extab_123
	.4byte 0x30080000
	.4byte 0
glabel extab_124
	.4byte 0x30080000
	.4byte 0
glabel extab_125
	.4byte 0x10080000
	.4byte 0
glabel extab_126
	.4byte 0x38080000
	.4byte 0
glabel extab_127
	.4byte 0x00080000
	.4byte 0
glabel extab_128
	.4byte 0x28080000
	.4byte 0
glabel extab_129
	.4byte 0x00080000
	.4byte 0
glabel extab_130
	.4byte 0x28080000
	.4byte 0
glabel extab_131
	.4byte 0x18080000
	.4byte 0
glabel extab_132
	.4byte 0x90080000
	.4byte 0
glabel extab_133
	.4byte 0x00080000
	.4byte 0
glabel extab_134
	.4byte 0x10080000
	.4byte 0
glabel extab_135
	.4byte 0x20080000
	.4byte 0
glabel extab_136
	.4byte 0x73080000
	.4byte 0
glabel extab_137
	.4byte 0x41080000
	.4byte 0
glabel extab_138
	.4byte 0x10880000
	.4byte 0
glabel extab_139
	.4byte 0x42080000
	.4byte 0
glabel extab_140
	.4byte 0x20C80000
	.4byte 0
glabel extab_141
	.4byte 0x00080000
	.4byte 0
glabel extab_142
	.4byte 0x20080000
	.4byte 0
glabel extab_143
	.4byte 0x21080000
	.4byte 0
glabel extab_144
	.4byte 0x18C80000
	.4byte 0
glabel extab_145
	.4byte 0x10080000
	.4byte 0
glabel extab_146
	.4byte 0x38080000
	.4byte 0
glabel extab_147
	.4byte 0x20080000
	.4byte 0
glabel extab_148
	.4byte 0x10080000
	.4byte 0
glabel extab_149
	.4byte 0x20080000
	.4byte 0
glabel extab_150
	.4byte 0x40080000
	.4byte 0
glabel extab_151
	.4byte 0x00080000
	.4byte 0
glabel extab_152
	.4byte 0x00080000
	.4byte 0
glabel extab_153
	.4byte 0x00080000
	.4byte 0
glabel extab_154
	.4byte 0x00080000
	.4byte 0
glabel extab_155
	.4byte 0x00080000
	.4byte 0
glabel extab_156
	.4byte 0x00080000
	.4byte 0
glabel extab_157
	.4byte 0x00080000
	.4byte 0
glabel extab_158
	.4byte 0x00080000
	.4byte 0
glabel extab_159
	.4byte 0x00080000
	.4byte 0
glabel extab_160
	.4byte 0x00080000
	.4byte 0
glabel extab_161
	.4byte 0x00080000
	.4byte 0
glabel extab_162
	.4byte 0x00080000
	.4byte 0
glabel extab_163
	.4byte 0x00080000
	.4byte 0
glabel extab_164
	.4byte 0x00080000
	.4byte 0
glabel extab_165
	.4byte 0x00080000
	.4byte 0
glabel extab_166
	.4byte 0x10080000
	.4byte 0
glabel extab_167
	.4byte 0x18080000
	.4byte 0
glabel extab_168
	.4byte 0x48080000
	.4byte 0
glabel extab_169
	.4byte 0x08080000
	.4byte 0
glabel extab_170
	.4byte 0x10080000
	.4byte 0
glabel extab_171
	.4byte 0x18080000
	.4byte 0
glabel extab_172
	.4byte 0x28080000
	.4byte 0
glabel extab_173
	.4byte 0x18080000
	.4byte 0
glabel extab_174
	.4byte 0x00080000
	.4byte 0
glabel extab_175
	.4byte 0x10080000
	.4byte 0
glabel extab_176
	.4byte 0x00080000
	.4byte 0
glabel extab_177
	.4byte 0x00080000
	.4byte 0
glabel extab_178
	.4byte 0x00080000
	.4byte 0
glabel extab_179
	.4byte 0x00080000
	.4byte 0
glabel extab_180
	.4byte 0x00080000
	.4byte 0
glabel extab_181
	.4byte 0x20080000
	.4byte 0
glabel extab_182
	.4byte 0x00080000
	.4byte 0
glabel extab_183
	.4byte 0x00080000
	.4byte 0
glabel extab_184
	.4byte 0x00080000
	.4byte 0
glabel extab_185
	.4byte 0x00080000
	.4byte 0
glabel extab_186
	.4byte 0x00080000
	.4byte 0
glabel extab_187
	.4byte 0x08080000
	.4byte 0
glabel extab_188
	.4byte 0x00080000
	.4byte 0
glabel extab_189
	.4byte 0x00080000
	.4byte 0
glabel extab_190
	.4byte 0x28080000
	.4byte 0
glabel extab_191
	.4byte 0x28080000
	.4byte 0
glabel extab_192
	.4byte 0x00080000
	.4byte 0
glabel extab_193
	.4byte 0x28080000
	.4byte 0
glabel extab_194
	.4byte 0x00080000
	.4byte 0
glabel extab_195
	.4byte 0x08080000
	.4byte 0
glabel extab_196
	.4byte 0x10080000
	.4byte 0
glabel extab_197
	.4byte 0x00080000
	.4byte 0
glabel extab_198
	.4byte 0x10080000
	.4byte 0
glabel extab_199
	.4byte 0x08080000
	.4byte 0
glabel extab_200
	.4byte 0x00080000
	.4byte 0
glabel extab_201
	.4byte 0x00080000
	.4byte 0
glabel extab_202
	.4byte 0x00080000
	.4byte 0
glabel extab_203
	.4byte 0x00080000
	.4byte 0
glabel extab_204
	.4byte 0x00080000
	.4byte 0
glabel extab_205
	.4byte 0x00080000
	.4byte 0
glabel extab_206
	.4byte 0x00080000
	.4byte 0
glabel extab_207
	.4byte 0x00080000
	.4byte 0
glabel extab_208
	.4byte 0x00080000
	.4byte 0
glabel extab_209
	.4byte 0x00080000
	.4byte 0
glabel extab_210
	.4byte 0x82080000
	.4byte 0
glabel extab_211
	.4byte 0x28C80000
	.4byte 0
glabel extab_212
	.4byte 0x38080000
	.4byte 0
glabel extab_213
	.4byte 0x08080000
	.4byte 0

.section _extabindex, "wa"  # 0x80005B80 - 0x800065A0
extabindex:
	# ROM: 0x10BE40
	.4byte seqStartPlay  ;# ptr
	.4byte 0x00000AA4
	.4byte extab_0  ;# ptr
	.4byte HandleMasterTrack  ;# ptr
	.4byte 0x0000009C
	.4byte extab_1  ;# ptr
	.4byte seqPause  ;# ptr
	.4byte 0x00000190
	.4byte extab_2  ;# ptr
	.4byte seqStop  ;# ptr
	.4byte 0x000001D4
	.4byte extab_3  ;# ptr
	.4byte seqKillInstancesByGroupID  ;# ptr
	.4byte 0x00000090
	.4byte extab_4  ;# ptr
	.4byte seqVolume  ;# ptr
	.4byte 0x0000019C
	.4byte extab_5  ;# ptr
	.4byte seqCrossFade  ;# ptr
	.4byte 0x00000534
	.4byte extab_6  ;# ptr
	.4byte HandleEvent  ;# ptr
	.4byte 0x00000778
	.4byte extab_7  ;# ptr
	.4byte InitTrackEvents  ;# ptr
	.4byte 0x000000A8
	.4byte extab_8  ;# ptr
	.4byte InitTrackEventsSection  ;# ptr
	.4byte 0x000000C4
	.4byte extab_9  ;# ptr
	.4byte HandleTrackEvents  ;# ptr
	.4byte 0x0000017C
	.4byte extab_10  ;# ptr
	.4byte seqHandle  ;# ptr
	.4byte 0x00000744
	.4byte extab_11  ;# ptr
	.4byte synthInitPortamento  ;# ptr
	.4byte 0x000000AC
	.4byte extab_12  ;# ptr
	.4byte do_voice_portamento  ;# ptr
	.4byte 0x000001F8
	.4byte extab_13  ;# ptr
	.4byte StartLayer  ;# ptr
	.4byte 0x000003EC
	.4byte extab_14  ;# ptr
	.4byte StartKeymap  ;# ptr
	.4byte 0x00000244
	.4byte extab_15  ;# ptr
	.4byte synthStartSound  ;# ptr
	.4byte 0x000001CC
	.4byte extab_16  ;# ptr
	.4byte LowPrecisionHandler  ;# ptr
	.4byte 0x000007CC
	.4byte extab_17  ;# ptr
	.4byte ZeroOffsetHandler  ;# ptr
	.4byte 0x00000698
	.4byte extab_18  ;# ptr
	.4byte EventHandler  ;# ptr
	.4byte 0x00000190
	.4byte extab_19  ;# ptr
	.4byte synthStartSynthJobHandling  ;# ptr
	.4byte 0x00000064
	.4byte extab_20  ;# ptr
	.4byte synthForceLowPrecisionUpdate  ;# ptr
	.4byte 0x00000044
	.4byte extab_21  ;# ptr
	.4byte synthKeyStateUpdate  ;# ptr
	.4byte 0x00000028
	.4byte extab_22  ;# ptr
	.4byte HandleJobQueue  ;# ptr
	.4byte 0x0000007C
	.4byte extab_23  ;# ptr
	.4byte HandleFaderTermination  ;# ptr
	.4byte 0x0000006C
	.4byte extab_24  ;# ptr
	.4byte synthHandle  ;# ptr
	.4byte 0x00000318
	.4byte extab_25  ;# ptr
	.4byte synthFXStart  ;# ptr
	.4byte 0x00000204
	.4byte extab_26  ;# ptr
	.4byte synthFXSetCtrl  ;# ptr
	.4byte 0x000000E8
	.4byte extab_27  ;# ptr
	.4byte synthFXSetCtrl14  ;# ptr
	.4byte 0x000000E8
	.4byte extab_28  ;# ptr
	.4byte synthFXCloneMidiSetup  ;# ptr
	.4byte 0x00000084
	.4byte extab_29  ;# ptr
	.4byte synthSendKeyOff  ;# ptr
	.4byte 0x0000008C
	.4byte extab_30  ;# ptr
	.4byte synthVolume  ;# ptr
	.4byte 0x00000410
	.4byte extab_31  ;# ptr
	.4byte synthHWMessageHandler  ;# ptr
	.4byte 0x00000060
	.4byte extab_32  ;# ptr
	.4byte synthInit  ;# ptr
	.4byte 0x000004EC
	.4byte extab_33  ;# ptr
	.4byte sndSeqSpeed  ;# ptr
	.4byte 0x00000048
	.4byte extab_34  ;# ptr
	.4byte sndSeqContinue  ;# ptr
	.4byte 0x00000038
	.4byte extab_35  ;# ptr
	.4byte sndSeqMute  ;# ptr
	.4byte 0x00000058
	.4byte extab_36  ;# ptr
	.4byte sndSeqVolume  ;# ptr
	.4byte 0x00000068
	.4byte extab_37  ;# ptr
	.4byte sndFXCtrl  ;# ptr
	.4byte 0x00000060
	.4byte extab_38  ;# ptr
	.4byte sndFXCtrl14  ;# ptr
	.4byte 0x00000060
	.4byte extab_39  ;# ptr
	.4byte sndFXKeyOff  ;# ptr
	.4byte 0x00000040
	.4byte extab_40  ;# ptr
	.4byte sndFXStartParaInfo  ;# ptr
	.4byte 0x000000D4
	.4byte extab_41  ;# ptr
	.4byte sndFXCheck  ;# ptr
	.4byte 0x00000044
	.4byte extab_42  ;# ptr
	.4byte sndVolume  ;# ptr
	.4byte 0x00000060
	.4byte extab_43  ;# ptr
	.4byte sndMasterVolume  ;# ptr
	.4byte 0x00000094
	.4byte extab_44  ;# ptr
	.4byte sndOutputMode  ;# ptr
	.4byte 0x00000080
	.4byte extab_45  ;# ptr
	.4byte sndSetAuxProcessingCallbacks  ;# ptr
	.4byte 0x00000168
	.4byte extab_46  ;# ptr
	.4byte synthActivateStudio  ;# ptr
	.4byte 0x000000AC
	.4byte extab_47  ;# ptr
	.4byte synthDeactivateStudio  ;# ptr
	.4byte 0x000000F0
	.4byte extab_48  ;# ptr
	.4byte synthAddStudioInput  ;# ptr
	.4byte 0x00000020
	.4byte extab_49  ;# ptr
	.4byte synthRemoveStudioInput  ;# ptr
	.4byte 0x00000020
	.4byte extab_50  ;# ptr
	.4byte streamHandle  ;# ptr
	.4byte 0x0000072C
	.4byte extab_51  ;# ptr
	.4byte streamKill  ;# ptr
	.4byte 0x00000084
	.4byte extab_52  ;# ptr
	.4byte sndStreamAllocEx  ;# ptr
	.4byte 0x00000414
	.4byte extab_53  ;# ptr
	.4byte sndStreamFree  ;# ptr
	.4byte 0x00000210
	.4byte extab_54  ;# ptr
	.4byte sndStreamActivate  ;# ptr
	.4byte 0x00000200
	.4byte extab_55  ;# ptr
	.4byte sndStreamDeactivate  ;# ptr
	.4byte 0x00000240
	.4byte extab_56  ;# ptr
	.4byte dataInsertKeymap  ;# ptr
	.4byte 0x000001F0
	.4byte extab_57  ;# ptr
	.4byte dataRemoveKeymap  ;# ptr
	.4byte 0x00000184
	.4byte extab_58  ;# ptr
	.4byte dataInsertLayer  ;# ptr
	.4byte 0x00000248
	.4byte extab_59  ;# ptr
	.4byte dataRemoveLayer  ;# ptr
	.4byte 0x000001CC
	.4byte extab_60  ;# ptr
	.4byte dataInsertCurve  ;# ptr
	.4byte 0x000001F8
	.4byte extab_61  ;# ptr
	.4byte dataRemoveCurve  ;# ptr
	.4byte 0x00000184
	.4byte extab_62  ;# ptr
	.4byte dataInsertSDir  ;# ptr
	.4byte 0x0000016C
	.4byte extab_63  ;# ptr
	.4byte dataRemoveSDir  ;# ptr
	.4byte 0x00000288
	.4byte extab_64  ;# ptr
	.4byte dataAddSampleReference  ;# ptr
	.4byte 0x000000D8
	.4byte extab_65  ;# ptr
	.4byte dataRemoveSampleReference  ;# ptr
	.4byte 0x000000E8
	.4byte extab_66  ;# ptr
	.4byte dataInsertFX  ;# ptr
	.4byte 0x00000128
	.4byte extab_67  ;# ptr
	.4byte dataRemoveFX  ;# ptr
	.4byte 0x0000015C
	.4byte extab_68  ;# ptr
	.4byte dataInsertMacro  ;# ptr
	.4byte 0x00000310
	.4byte extab_69  ;# ptr
	.4byte dataRemoveMacro  ;# ptr
	.4byte 0x0000029C
	.4byte extab_70  ;# ptr
	.4byte dataGetMacro  ;# ptr
	.4byte 0x00000094
	.4byte extab_71  ;# ptr
	.4byte dataGetSample  ;# ptr
	.4byte 0x00000128
	.4byte extab_72  ;# ptr
	.4byte dataGetCurve  ;# ptr
	.4byte 0x00000060
	.4byte extab_73  ;# ptr
	.4byte dataGetKeymap  ;# ptr
	.4byte 0x00000060
	.4byte extab_74  ;# ptr
	.4byte dataGetLayer  ;# ptr
	.4byte 0x00000080
	.4byte extab_75  ;# ptr
	.4byte dataGetFX  ;# ptr
	.4byte 0x000000A8
	.4byte extab_76  ;# ptr
	.4byte dataInit  ;# ptr
	.4byte 0x000000E4
	.4byte extab_77  ;# ptr
	.4byte mcmdWait  ;# ptr
	.4byte 0x00000308
	.4byte extab_78  ;# ptr
	.4byte mcmdLoop  ;# ptr
	.4byte 0x00000158
	.4byte extab_79  ;# ptr
	.4byte mcmdPlayMacro  ;# ptr
	.4byte 0x00000198
	.4byte extab_80  ;# ptr
	.4byte mcmdStartSample  ;# ptr
	.4byte 0x000001E4
	.4byte extab_81  ;# ptr
	.4byte mcmdVibrato  ;# ptr
	.4byte 0x00000180
	.4byte extab_82  ;# ptr
	.4byte mcmdSetADSR  ;# ptr
	.4byte 0x00000258
	.4byte extab_83  ;# ptr
	.4byte mcmdSetPitchADSR  ;# ptr
	.4byte 0x00000280
	.4byte extab_84  ;# ptr
	.4byte DoPanningSetup  ;# ptr
	.4byte 0x000000A0
	.4byte extab_85  ;# ptr
	.4byte TranslateVolume  ;# ptr
	.4byte 0x00000080
	.4byte extab_86  ;# ptr
	.4byte DoEnvelopeCalculation  ;# ptr
	.4byte 0x0000012C
	.4byte extab_87  ;# ptr
	.4byte mcmdRandomKey  ;# ptr
	.4byte 0x000001A0
	.4byte extab_88  ;# ptr
	.4byte SelectSource  ;# ptr
	.4byte 0x00000134
	.4byte extab_89  ;# ptr
	.4byte mcmdPortamento  ;# ptr
	.4byte 0x0000011C
	.4byte extab_90  ;# ptr
	.4byte varGet32  ;# ptr
	.4byte 0x00000064
	.4byte extab_91  ;# ptr
	.4byte varGet  ;# ptr
	.4byte 0x00000068
	.4byte extab_92  ;# ptr
	.4byte varSet32  ;# ptr
	.4byte 0x00000064
	.4byte extab_93  ;# ptr
	.4byte mcmdVarCalculation  ;# ptr
	.4byte 0x00000130
	.4byte extab_94  ;# ptr
	.4byte mcmdSendMessage  ;# ptr
	.4byte 0x00000234
	.4byte extab_95  ;# ptr
	.4byte mcmdSetKeyGroup  ;# ptr
	.4byte 0x000000D4
	.4byte extab_96  ;# ptr
	.4byte macHandleActive  ;# ptr
	.4byte 0x000014B4
	.4byte extab_97  ;# ptr
	.4byte macHandle  ;# ptr
	.4byte 0x00000148
	.4byte extab_98  ;# ptr
	.4byte macSampleEndNotify  ;# ptr
	.4byte 0x000000B0
	.4byte extab_99  ;# ptr
	.4byte macSetExternalKeyoff  ;# ptr
	.4byte 0x000000F4
	.4byte extab_100  ;# ptr
	.4byte macSetPedalState  ;# ptr
	.4byte 0x0000010C
	.4byte extab_101  ;# ptr
	.4byte UnYieldMacro  ;# ptr
	.4byte 0x000000DC
	.4byte extab_102  ;# ptr
	.4byte macMakeActive  ;# ptr
	.4byte 0x00000108
	.4byte extab_103  ;# ptr
	.4byte macStart  ;# ptr
	.4byte 0x00000310
	.4byte extab_104  ;# ptr
	.4byte vidRemoveVoiceReferences  ;# ptr
	.4byte 0x00000354
	.4byte extab_105  ;# ptr
	.4byte voiceSetPriority  ;# ptr
	.4byte 0x00000190
	.4byte extab_106  ;# ptr
	.4byte voiceFree  ;# ptr
	.4byte 0x000000E4
	.4byte extab_107  ;# ptr
	.4byte voiceBlock  ;# ptr
	.4byte 0x000000E8
	.4byte extab_109  ;# ptr
	.4byte voiceUnblock  ;# ptr
	.4byte 0x00000080
	.4byte extab_110  ;# ptr
	.4byte voiceKill  ;# ptr
	.4byte 0x000000A0
	.4byte extab_111  ;# ptr
	.4byte voiceKillSound  ;# ptr
	.4byte 0x00000110
	.4byte extab_112  ;# ptr
	.4byte synthKillVoicesByMacroReferences  ;# ptr
	.4byte 0x00000140
	.4byte extab_113  ;# ptr
	.4byte sndGetPitch  ;# ptr
	.4byte 0x000000F0
	.4byte extab_114  ;# ptr
	.4byte adsrConvertTimeCents  ;# ptr
	.4byte 0x00000054
	.4byte extab_115  ;# ptr
	.4byte adsrSetup  ;# ptr
	.4byte 0x00000028
	.4byte extab_116  ;# ptr
	.4byte adsrStartRelease  ;# ptr
	.4byte 0x00000154
	.4byte extab_117  ;# ptr
	.4byte adsrRelease  ;# ptr
	.4byte 0x00000044
	.4byte extab_118  ;# ptr
	.4byte adsrHandle  ;# ptr
	.4byte 0x000001A0
	.4byte extab_119  ;# ptr
	.4byte adsrHandleLowPrecision  ;# ptr
	.4byte 0x00000084
	.4byte extab_120  ;# ptr
	.4byte InsertData  ;# ptr
	.4byte 0x000001F0
	.4byte extab_121  ;# ptr
	.4byte ScanIDList  ;# ptr
	.4byte 0x0000009C
	.4byte extab_122  ;# ptr
	.4byte ScanIDListReverse  ;# ptr
	.4byte 0x000000F0
	.4byte extab_123  ;# ptr
	.4byte sndPushGroup  ;# ptr
	.4byte 0x0000016C
	.4byte extab_124  ;# ptr
	.4byte sndPopGroup  ;# ptr
	.4byte 0x00000128
	.4byte extab_125  ;# ptr
	.4byte seqPlaySong  ;# ptr
	.4byte 0x00000140
	.4byte extab_126  ;# ptr
	.4byte sndSeqPlayEx  ;# ptr
	.4byte 0x00000028
	.4byte extab_127  ;# ptr
	.4byte salInitDspCtrl  ;# ptr
	.4byte 0x00000378
	.4byte extab_128  ;# ptr
	.4byte salInitHRTFBuffer  ;# ptr
	.4byte 0x00000038
	.4byte extab_129  ;# ptr
	.4byte salActivateStudio  ;# ptr
	.4byte 0x00000108
	.4byte extab_130  ;# ptr
	.4byte SortVoices  ;# ptr
	.4byte 0x000000FC
	.4byte extab_131  ;# ptr
	.4byte salBuildCommandList  ;# ptr
	.4byte 0x0000251C
	.4byte extab_132  ;# ptr
	.4byte salSynthSendMessage  ;# ptr
	.4byte 0x0000003C
	.4byte extab_133  ;# ptr
	.4byte salActivateVoice  ;# ptr
	.4byte 0x000000A0
	.4byte extab_134  ;# ptr
	.4byte salHandleAuxProcessing  ;# ptr
	.4byte 0x0000015C
	.4byte extab_135  ;# ptr
	.4byte salCalcVolume  ;# ptr
	.4byte 0x00000798
	.4byte extab_136  ;# ptr
	.4byte CheckRoomStatus  ;# ptr
	.4byte 0x000003DC
	.4byte extab_137  ;# ptr
	.4byte CheckDoorStatus  ;# ptr
	.4byte 0x000001DC
	.4byte extab_138  ;# ptr
	.4byte CalcEmitter  ;# ptr
	.4byte 0x000004BC
	.4byte extab_139  ;# ptr
	.4byte SetFXParameters  ;# ptr
	.4byte 0x00000220
	.4byte extab_140  ;# ptr
	.4byte EmitterShutdown  ;# ptr
	.4byte 0x00000070
	.4byte extab_141  ;# ptr
	.4byte s3dKillEmitterByFXID  ;# ptr
	.4byte 0x000000B0
	.4byte extab_142  ;# ptr
	.4byte StartContinousEmitters  ;# ptr
	.4byte 0x000001EC
	.4byte extab_143  ;# ptr
	.4byte s3dHandle  ;# ptr
	.4byte 0x00000364
	.4byte extab_144  ;# ptr
	.4byte sndActive  ;# ptr
	.4byte 0x000000D8
	.4byte extab_145  ;# ptr
	.4byte inpSetMidiCtrl  ;# ptr
	.4byte 0x000005D0
	.4byte extab_146  ;# ptr
	.4byte inpSetMidiCtrl14  ;# ptr
	.4byte 0x00000128
	.4byte extab_147  ;# ptr
	.4byte inpResetMidiCtrl  ;# ptr
	.4byte 0x00000104
	.4byte extab_148  ;# ptr
	.4byte inpAddCtrl  ;# ptr
	.4byte 0x0000009C
	.4byte extab_149  ;# ptr
	.4byte _GetInputValue  ;# ptr
	.4byte 0x00000488
	.4byte extab_150  ;# ptr
	.4byte inpGetVolume  ;# ptr
	.4byte 0x00000048
	.4byte extab_151  ;# ptr
	.4byte inpGetPanning  ;# ptr
	.4byte 0x00000048
	.4byte extab_152  ;# ptr
	.4byte inpGetSurPanning  ;# ptr
	.4byte 0x00000048
	.4byte extab_153  ;# ptr
	.4byte inpGetPitchBend  ;# ptr
	.4byte 0x00000048
	.4byte extab_154  ;# ptr
	.4byte inpGetDoppler  ;# ptr
	.4byte 0x00000048
	.4byte extab_155  ;# ptr
	.4byte inpGetModulation  ;# ptr
	.4byte 0x00000048
	.4byte extab_156  ;# ptr
	.4byte inpGetPedal  ;# ptr
	.4byte 0x00000048
	.4byte extab_157  ;# ptr
	.4byte inpGetPortamento  ;# ptr
	.4byte 0x00000048
	.4byte extab_158  ;# ptr
	.4byte inpGetPreAuxA  ;# ptr
	.4byte 0x00000048
	.4byte extab_159  ;# ptr
	.4byte inpGetReverb  ;# ptr
	.4byte 0x00000048
	.4byte extab_160  ;# ptr
	.4byte inpGetPreAuxB  ;# ptr
	.4byte 0x00000048
	.4byte extab_161  ;# ptr
	.4byte inpGetPostAuxB  ;# ptr
	.4byte 0x00000048
	.4byte extab_162  ;# ptr
	.4byte inpGetTremolo  ;# ptr
	.4byte 0x00000048
	.4byte extab_163  ;# ptr
	.4byte inpGetAuxA  ;# ptr
	.4byte 0x000000BC
	.4byte extab_164  ;# ptr
	.4byte inpGetAuxB  ;# ptr
	.4byte 0x000000BC
	.4byte extab_165  ;# ptr
	.4byte inpGetExCtrl  ;# ptr
	.4byte 0x000000A0
	.4byte extab_166  ;# ptr
	.4byte inpSetExCtrl  ;# ptr
	.4byte 0x00000098
	.4byte extab_167  ;# ptr
	.4byte sndBSearch  ;# ptr
	.4byte 0x00000098
	.4byte extab_168  ;# ptr
	.4byte sndConvertTicks  ;# ptr
	.4byte 0x00000048
	.4byte extab_169  ;# ptr
	.4byte snd_handle_irq  ;# ptr
	.4byte 0x00000158
	.4byte extab_170  ;# ptr
	.4byte hwInit  ;# ptr
	.4byte 0x000000B4
	.4byte extab_171  ;# ptr
	.4byte hwInitSamplePlayback  ;# ptr
	.4byte 0x000001AC
	.4byte extab_172  ;# ptr
	.4byte hwSetADSR  ;# ptr
	.4byte 0x000001B0
	.4byte extab_173  ;# ptr
	.4byte hwStart  ;# ptr
	.4byte 0x0000003C
	.4byte extab_174  ;# ptr
	.4byte hwSetVolume  ;# ptr
	.4byte 0x000002D0
	.4byte extab_175  ;# ptr
	.4byte hwOff  ;# ptr
	.4byte 0x0000002C
	.4byte extab_176  ;# ptr
	.4byte hwActivateStudio  ;# ptr
	.4byte 0x00000020
	.4byte extab_177  ;# ptr
	.4byte hwDeactivateStudio  ;# ptr
	.4byte 0x00000020
	.4byte extab_178  ;# ptr
	.4byte hwAddInput  ;# ptr
	.4byte 0x00000034
	.4byte extab_179  ;# ptr
	.4byte hwRemoveInput  ;# ptr
	.4byte 0x00000034
	.4byte extab_180  ;# ptr
	.4byte hwFlushStream  ;# ptr
	.4byte 0x00000090
	.4byte extab_181  ;# ptr
	.4byte hwInitStream  ;# ptr
	.4byte 0x00000020
	.4byte extab_182  ;# ptr
	.4byte hwExitStream  ;# ptr
	.4byte 0x00000020
	.4byte extab_183  ;# ptr
	.4byte hwGetStreamPlayBuffer  ;# ptr
	.4byte 0x00000024
	.4byte extab_184  ;# ptr
	.4byte hwFrq2Pitch  ;# ptr
	.4byte 0x0000005C
	.4byte extab_185  ;# ptr
	.4byte hwInitSampleMem  ;# ptr
	.4byte 0x00000024
	.4byte extab_186  ;# ptr
	.4byte hwSaveSample  ;# ptr
	.4byte 0x00000094
	.4byte extab_187  ;# ptr
	.4byte hwRemoveSample  ;# ptr
	.4byte 0x00000084
	.4byte extab_188  ;# ptr
	.4byte hwSyncSampleMem  ;# ptr
	.4byte 0x00000020
	.4byte extab_189  ;# ptr
	.4byte aramUploadData  ;# ptr
	.4byte 0x00000170
	.4byte extab_190  ;# ptr
	.4byte aramInit  ;# ptr
	.4byte 0x0000031C
	.4byte extab_191  ;# ptr
	.4byte aramGetZeroBuffer  ;# ptr
	.4byte 0x00000020
	.4byte extab_192  ;# ptr
	.4byte aramStoreData  ;# ptr
	.4byte 0x00000178
	.4byte extab_193  ;# ptr
	.4byte salCallback  ;# ptr
	.4byte 0x000000A4
	.4byte extab_194  ;# ptr
	.4byte dspResumeCallback  ;# ptr
	.4byte 0x00000068
	.4byte extab_195  ;# ptr
	.4byte salInitAi  ;# ptr
	.4byte 0x000000CC
	.4byte extab_196  ;# ptr
	.4byte salStartAi  ;# ptr
	.4byte 0x00000020
	.4byte extab_197  ;# ptr
	.4byte salInitDsp  ;# ptr
	.4byte 0x000000C0
	.4byte extab_198  ;# ptr
	.4byte salCtrlDsp  ;# ptr
	.4byte 0x00000074
	.4byte extab_199  ;# ptr
	.4byte salGetStartDelay  ;# ptr
	.4byte 0x0000004C
	.4byte extab_200  ;# ptr
	.4byte hwInitIrq  ;# ptr
	.4byte 0x0000002C
	.4byte extab_201  ;# ptr
	.4byte hwEnableIrq  ;# ptr
	.4byte 0x00000038
	.4byte extab_202  ;# ptr
	.4byte hwDisableIrq  ;# ptr
	.4byte 0x00000038
	.4byte extab_203  ;# ptr
	.4byte hwIRQEnterCritical  ;# ptr
	.4byte 0x00000020
	.4byte extab_204  ;# ptr
	.4byte hwIRQLeaveCritical  ;# ptr
	.4byte 0x00000020
	.4byte extab_205  ;# ptr
	.4byte salMalloc  ;# ptr
	.4byte 0x00000028
	.4byte extab_206  ;# ptr
	.4byte salFree  ;# ptr
	.4byte 0x0000002C
	.4byte extab_207  ;# ptr
	.4byte sndAuxCallbackReverbHI  ;# ptr
	.4byte 0x0000005C
	.4byte extab_208  ;# ptr
	.4byte sndAuxCallbackPrepareReverbHI  ;# ptr
	.4byte 0x00000040
	.4byte extab_209  ;# ptr
	.4byte ReverbHICreate  ;# ptr
	.4byte 0x000004CC
	.4byte extab_210  ;# ptr
	.4byte ReverbHICallback  ;# ptr
	.4byte 0x000000F8
	.4byte extab_211  ;# ptr
	.4byte sndAuxCallbackChorus  ;# ptr
	.4byte 0x0000036C
	.4byte extab_212  ;# ptr
	.4byte sndAuxCallbackPrepareChorus  ;# ptr
	.4byte 0x00000260
	.4byte extab_213  ;# ptr

.global TODO_eti_init_info
TODO_eti_init_info:
	# ROM: 0x10C83C
	.4byte _f_extabindex  ;# ptr
	.4byte TODO_eti_init_info  ;# ptr
	.4byte seqStartPlay  ;# ptr
	.4byte 0x00019FE0
	.4byte 0
	.4byte 0
	.4byte 0
	.4byte 0


.section .ctors, "wa"  # 0x8010F860 - 0x8010F880
.global __init_cpp_exceptions_reference
__init_cpp_exceptions_reference:
	# ROM: 0x10C860
	.4byte __init_cpp_exceptions  ;# ptr
	.4byte __sinit_trigf_c  ;# ptr
	.4byte 0

.section .dtors, "wa"  # 0x8010F880 - 0x8010F8A0
__dtors:
	# ROM: 0x10C880
	.4byte __destroy_global_chain  ;# ptr
	.4byte __fini_cpp_exceptions  ;# ptr
	.4byte __destroy_global_chain  ;# ptr
