void camera_init(void);
void ev_camera_init(void);
void ev_camera_main(void);
void ev_camera_dest(void);
void func_80017FCC(void);
void setup_camera_viewport(int cameraId, float left, float top, float width, float height);
void camera_setup_splitscreen_viewports(int playerCount);
void camera_setup_singleplayer_viewport(void);
void func_80018330(int);
void func_80018648();
// ? func_80018680();
// ? func_800188A8();
void func_800188D4(void);
// ? func_8001898C();
void camera_set_state(int state);
void camera_set_or_clear_flags(int flags, int set);
void camera_clear(struct Camera *camera);
void func_80018C58(struct Camera *camera);
void camera_sub_27(struct Camera *camera, struct Ball *ball);
void camera_sub_28(struct Camera *camera, struct Ball *ball);
void camera_sub_29(struct Camera *camera, struct Ball *ball);
void camera_sub_30(struct Camera *camera, struct Ball *ball);
void camera_sub_54(struct Camera *camera, struct Ball *ball);
void camera_sub_55(struct Camera *camera, struct Ball *ball);
void camera_sub_43(struct Camera *camera, struct Ball *ball);
void camera_sub_12(struct Camera *camera, struct Ball *ball);
void camera_sub_13(struct Camera *camera, struct Ball *ball);
void camera_sub_52(struct Camera *camera, struct Ball *ball);
void camera_sub_53(struct Camera *camera, struct Ball *ball);
void camera_sub_ready_init(struct Camera *camera, struct Ball *ball);
void camera_sub_ready_main(struct Camera *camera, struct Ball *ball);
void camera_sub_38(struct Camera *camera, struct Ball *ball);
void func_80019CDC(Quaternion *);
void camera_sub_0(struct Camera *camera, struct Ball *ball);
void camera_sub_1(struct Camera *camera, struct Ball *ball);
void camera_sub_2(struct Camera *camera, struct Ball *ball);
void camera_sub_3(struct Camera *camera, struct Ball *ball);
void camera_sub_62(struct Camera *camera, struct Ball *ball);
void camera_sub_4(struct Camera *camera, struct Ball *ball);
void camera_sub_5(struct Camera *camera, struct Ball *ball);
void camera_sub_6(struct Camera *camera, struct Ball *ball);
void camera_sub_7(struct Camera *camera, struct Ball *ball);
void camera_sub_ringout_main(struct Camera *camera, struct Ball *ball);
void camera_sub_9(struct Camera *camera, struct Ball *ball);
void camera_sub_14(struct Camera *camera, struct Ball *ball);
void camera_sub_goal_main(struct Camera *camera, struct Ball *ball);
void camera_sub_16(struct Camera *camera, struct Ball *ball);
void camera_sub_17(struct Camera *camera, struct Ball *ball);
void camera_sub_18(struct Camera *camera, struct Ball *ball);
void camera_sub_19(struct Camera *camera, struct Ball *ball);
void camera_sub_20(struct Camera *camera, struct Ball *ball);
void camera_sub_21(struct Camera *camera, struct Ball *ball);
void camera_sub_22_23_24(struct Camera *camera, struct Ball *ball);
void camera_sub_25(struct Camera *camera, struct Ball *ball);
void camera_sub_26(struct Camera *camera, struct Ball *ball);
void camera_sub_31(struct Camera *camera, struct Ball *ball);
void camera_sub_32(struct Camera *camera, struct Ball *ball);
void camera_sub_33(struct Camera *camera, struct Ball *ball);
void camera_sub_34(struct Camera *camera, struct Ball *ball);
void camera_sub_35(struct Camera *camera, struct Ball *ball);
void camera_sub_36(struct Camera *camera, struct Ball *ball);
void camera_sub_37(struct Camera *camera, struct Ball *ball);
void camera_sub_39(struct Camera *camera, struct Ball *ball);
void camera_sub_40(struct Camera *camera, struct Ball *ball);
void camera_sub_41(struct Camera *camera, struct Ball *ball);
void camera_sub_42(struct Camera *camera, struct Ball *ball);
void camera_sub_44(struct Camera *camera, struct Ball *ball);
void camera_sub_45(struct Camera *camera, struct Ball *ball);
void camera_sub_46(struct Camera *camera, struct Ball *ball);
void camera_sub_47(struct Camera *camera, struct Ball *ball);
void camera_sub_48(struct Camera *camera, struct Ball *ball);
void camera_sub_49(struct Camera *camera, struct Ball *ball);
void camera_sub_50(struct Camera *camera, struct Ball *ball);
void camera_sub_51(struct Camera *camera, struct Ball *ball);
void camera_sub_56(struct Camera *camera, struct Ball *ball);
void camera_sub_57(struct Camera *camera, struct Ball *ball);
void camera_sub_63(struct Camera *camera, struct Ball *ball);
void camera_sub_66(struct Camera *camera, struct Ball *ball);
void camera_sub_68(struct Camera *camera, struct Ball *ball);
void camera_sub_69(struct Camera *camera, struct Ball *ball);
void func_8001FF2C(struct Camera *, struct Ball *, Vec *, Vec *, s16 *, s16 *, s16 *, int);
void func_80020334(struct Camera *, struct Ball *, Vec *, Vec *, s16 *, s16 *, s16 *);
void camera_sub_70(struct Camera *camera, struct Ball *ball);
void camera_sub_71(struct Camera *camera, struct Ball *ball);
void camera_sub_72(struct Camera *camera, struct Ball *ball);
void camera_sub_73(struct Camera *camera, struct Ball *ball);
void camera_sub_mini(struct Camera *camera, struct Ball *ball);
