#ifndef _SRC_FUNCTIONS_H_
#define _SRC_FUNCTIONS_H_

#include "types.h"

// ? main();
void initialize(void);
void init_gx(void);
void init_tv(void);
void init_vi(void);
void init_gx_2(void);
void init_dvd(void);
void init_heaps(void);
void init_rel(void);
void init_cache(void);
void init_cache_ptrs(void);

// ? title_screen_debug_menu();
void u_menu_input_debug(void);
void u_menu_input_notdebug(void);
void submode_dummy_func(void);
int should_open_pause_menu(void);
// ? u_open_pause_menu();
// ? u_handle_pause_menu_navigation();
// ? u_pause_menu_load_how_to_play();
// ? u_activate_pause_menu_item();
// ? unkFunc8000AECC();
void u_menu_input_game_notdebug(void);

void polydisp_init(void);
void polydisp_main(void);
void draw_3d_scene(void);
void draw_adv_3d_scene(void);
void draw_intro_av_logo(void);
void draw_adv_demo_scene(void);
void u_draw_tutorial_button_and_joystick(void);
// ? func_8000C144();
void func_8000C388(void);
void draw_normal_game_scene(void);
void func_8000C7A4(void);
void func_8000C8D4(void);
void draw_continue_scene(void);
void draw_extra_scene(void);
void draw_results_scene(void);
void draw_test_camera_target(void);
void func_8000D5B8(void);
void draw_timer_bomb_fuse(void);
void set_backdrop_color(void);
void draw_monkey(void);
void func_8000E134(void);
void func_8000E180(void);
void func_8000E1A4(float);
void func_8000E338(int);
void u_reset_post_mult_color(void);
void func_8000E428(float a, float b, float c);
float func_8000E444(Vec *);
float func_8000E4D0(Vec *);
float func_8000E53C(Vec *pos);

void u_reset_gamedata(void);
void u_store_gamedata();
void u_load_gamedata();

void mode_sel_func(void);
void func_800123DC(void);
void submode_sel_ngc_dest_func(void);
void func_80012434(int);
void func_80012510(void (*a)(void), void (*b)(void), BallCallback ballcb, CameraCallback cameracb);
void submode_sel_init_func(void);
void submode_sel_main_func(void);
void func_800125A4(void);

void func_80020AB8(Vec *, S16Vec *, float, float, float, float);
// ? func_80020DB4();
BOOL test_sphere_in_frustum(Point3d *p, float radius);
BOOL test_scaled_sphere_in_frustum(Point3d *p, float radius, float scale);

void init_wait_vblank(void);
void beginframe_main(void);
void gpwait_main(void);
void syncwait_main(void);

int load_common_graphics(void);
void func_800249D4(void);
void u_free_minigame_graphics(void);

// ? func_800274E8();
// ? func_800275A0();
// ? func_8002773C();
// ? func_8002786C();
// ? func_80028978();
// ? func_800289A0();
void sound_init(void);
void sound_main(void);
// ? func_80029228();
void func_80029788(void);
void ev_sound_init(void);
void ev_sound_main(void);
void ev_sound_dest(void);
// ? func_8002A22C();
// ? func_8002A324();
// ? func_8002A34C();
// ? func_8002A964();
// ? func_8002ABF0();
// ? func_8002AE58();
// ? SoundReq();
// ? SoundReqDirect();
// ? SoundReqID();
void u_play_sound(int);
void func_8002B5C8(int);
// ? func_8002B5EC();
int func_8002B610(int);
// ? func_8002B634();
// ? func_8002BB20();
void func_8002BFCC(int, int);
// ? SoundOff();
void SoundPan(int, int, int);
void SoundPitch(u16, int);
// ? SoundSearchID();
// ? SoundOffID();
void SoundRevID(int, int);
void SoundChoID(int, int);
// ? func_8002CA38();
void func_8002CA5C(int, s8, s8);
// ? func_8002CEB8();
void u_play_music(int, int);
void func_8002DB10();
void func_8002DB24();
void func_8002DB38();
void func_8002DBC4(void);
// ? func_8002DC54();
// ? func_8002DD5C();
// ? func_8002DE38();
// ? func_8002E06C();
// ? func_8002E284();
// ? func_8002EA40();
// ? func_8002EF0C();
void func_8002F0E4(void);
void window_init(void);
void window_main(void);
void u_debug_set_cursor_pos(int, int);
// ? func_8002FC90();
// ? func_8002FCAC();
void func_8002FCC0(int, char *, ...);
void u_debug_set_text_color(int);
void func_8002FD68(int, const char *);
void func_8002FFEC(void);
// ? func_80030030();
void u_debug_printf(const char *, ...);
void u_debug_print();
void func_8003026C(int, char *, ...);
// ? func_80030310();
// ? func_800304E0();
void debug_main(void);
void chkstatus_init(void);
void chkstatus_main(void);
// ? func_800308AC();
// ? func_80030914();
// ? func_8003099C();
int pool_alloc();
void func_80030A50(void *);

void func_800341BC(struct JointBoneThing *a, struct MotSkeletonEntry1 *b, u16 c);
void func_80034360(struct JointBoneThing *a, u16 b);
// ? u_clear_mot_transforms();
// ? u_load_mot_transforms();
// ? u_read_transform_list_from_dat();
int init_ape_model_info(char *, char *, char *, char *);
void adjust_motdat_pointers(struct MotDat *);
void adjust_motlabel_pointers(u32 *);
void adjust_motskl_pointers(struct MotSkeleton *);
void adjust_motinfo_pointers(struct MotInfo *);
u16 func_80034F44(u16 index);
void u_interpolate_joint_motion(struct JointBoneThing *a, const struct Struct80034F5C_3 *b, const struct Struct80034F5C_2 *c, float e, u32 d);
void u_interp_pos_motion(struct JointBoneThing *, struct JointBoneThing *, u32, float);
void u_interp_rot_motion(struct JointBoneThing *, struct JointBoneThing *, const struct Struct80034F5C_3 *, u32, float);
float u_interp_skelanim_value_maybe(struct MotionTransform *, float);
float u_crazy_interpolation_stuff(Vec *, Vec *, float);
void read_transform_values(struct MotionTransform *, float *, float *, float *);
void u_skelanim_seek_next(struct MotionTransform *);
void u_skelanim_seek_prev(struct MotionTransform *);
void func_800355B8(struct Struct8003699C_child *);
void func_800355FC(struct Struct8003699C_child *);
void func_80035648(struct Struct8003699C_child *);
void func_80035748();
// ? func_80035B14();
// ? func_80035DEC();
// ? func_80035E7C();
void func_80035F18(struct Struct8003699C_child_sub *arg0, struct Struct8003699C_child *arg1, s32 arg2, u16 arg3);
void func_80035FDC(struct Struct8003699C_child *);
void func_80036064(struct Struct8003699C_child *);
void func_80036510(struct Struct8003699C_child_sub *);
// ? func_80036544();
// ? func_800366F8();
// ? func_80036720();
void func_800367E4(struct JointBoneThing *arg0, u16 arg1, u16 arg2);

float interpolate_keyframes(int count, struct Keyframe *frames, float time);

void draw_stage_preview(void);
void u_apply_func_to_nl_model_vertices(struct NlModel *model, void (*b)(struct NlVtxTypeB *), void (*c)(struct NlVtxTypeA *));
void u_apply_func_to_nl_disp_list_type_b(struct NlDispList *dl, void *end, void (*func)(struct NlVtxTypeB *));
void u_apply_func_to_nl_disp_list_type_a(struct NlDispList *dl, void *end, void (*func)(struct NlVtxTypeA *));
// ? func_80048084();
void func_80048420();
void func_800487B4(void);
void func_800489F8(void);
void func_80048BD4(void);
void ev_recplay_init(void);
void ev_recplay_main(void);
void ev_recplay_dest(void);
int func_80048E78(void);
void func_80048F20(void);
void func_80048F58(int, int);
void func_80048F74(void);
void func_80049158(void);
void func_8004923C(int);
void func_80049268(int);
void func_800492FC(int);
void func_80049368(int);
void func_800493C4(int);
// ? func_80049430();
void func_80049514(int);
float func_8004964C(int);
void func_800496BC(u32, struct Struct800496BC *, float);
void func_80049C1C(int, void *, float);
float func_80049E7C(int, float);
void u_get_replay_info(int, struct ReplayInfo *);
float func_80049F90(float, u32);
// ? func_8004A820();
// ? func_8004A874();
// ? func_8004AA18();
// ? func_8004ABD8();
// ? func_8004ABE4();
// ? func_8004AC68();
// ? func_8004ACF0();
// ? func_8004AD78();
// ? func_8004ADC0();
// ? func_8004AEA0();
// ? func_8004AFB8();
// ? func_8004AFC0();
// ? func_8004AFD0();
// ? func_8004AFD4();
// ? func_8004AFD8();
// ? func_8004B334();
// ? func_8004B354();
// ? func_8004B540();
// ? func_8004B550();
// ? func_8004B5AC();
// ? func_8004B60C();
void func_8004B65C(void);
// ? func_8004B694();
// ? func_8004B6C8();
// ? func_8004B70C();
// ? func_8004B81C();
// ? func_8004B850();
// ? func_8004BC1C();
// ? func_8004BFCC();
// ? func_8004C180();
// ? func_8004C1D8();
// ? func_8004C254();
// ? func_8004C28C();
// ? func_8004C2D8();
// ? func_8004C548();
u32 func_8004C668(void);
void func_8004C69C();
int func_8004C6DC();
int func_8004C70C(void);
void func_8004C754(void);
void func_8004C780(void);
void func_8004C7A8(void);
void u_give_points(int, int);
void ev_effect_init(void);
void ev_effect_main(void);
void ev_effect_dest(void);
void effect_draw(void);
void spawn_effect(struct Effect *);
void func_8004CFF0(int);
// ? func_8004D054();
// ? func_8004D194();
// ? func_8004D198();
// ? func_8004D19C();
// ? func_8004D1A0();
// ? func_8004D1A4();
// ? func_8004D2C8();
// ? func_8004D9AC();
// ? func_8004DB40();
// ? func_8004DB44();
// ? func_8004DC28();
// ? func_8004DD88();
// ? func_8004DE18();
// ? func_8004DE1C();
// ? func_8004DF0C();
// ? func_8004E384();
// ? func_8004E6F0();
// ? func_8004E6F4();
// ? func_8004E6F8();
// ? func_8004E748();
// ? func_8004E7C8();
// ? func_8004E7D4();
// ? func_8004E804();
// ? func_8004E96C();
// ? func_8004EAB8();
// ? func_8004EABC();
// ? func_8004EB38();
// ? func_8004EDD0();
// ? func_8004EE54();
// ? func_8004EE58();
// ? func_8004EF10();
// ? func_8004F17C();
// ? func_8004F1E8();
// ? func_8004F1EC();
// ? func_8004F36C();
// ? func_8004F3F4();
// ? func_8004F56C();
// ? func_8004F570();
// ? func_8004F584();
// ? func_8004F648();
// ? func_8004F78C();
// ? func_8004F790();
// ? func_8004F820();
// ? func_8004FB24();
// ? func_8004FC80();
// ? func_8004FC84();
// ? func_8004FD14();
// ? func_8004FDCC();
// ? func_8004FEBC();
// ? func_8004FEC0();
// ? func_8004FFD0();
// ? func_80050138();
// ? func_80050280();
// ? func_80050284();
// ? func_800504B0();
// ? func_800505E8();
// ? func_800506F0();
// ? func_800506F4();
// ? func_80050708();
// ? func_80050788();
// ? func_80050880();
// ? func_80050884();
// ? func_80050890();
// ? func_80050C38();
// ? func_80050D98();
// ? func_80050D9C();
// ? func_80050E1C();
// ? func_80050ED4();
// ? func_80050FB0();
// ? func_80050FB4();
// ? func_800510EC();
// ? func_800516DC();
// ? func_80051B98();
// ? func_80051B9C();
// ? func_80051C1C();
// ? func_80052014();
// ? func_80052018();
// ? func_8005201C();
// ? func_80052034();
// ? func_800522EC();
// ? func_800523F0();
// ? func_800523F4();
// ? func_80052414();
// ? func_80052918();
// ? func_80052A0C();
// ? func_80052A10();
// ? func_80052A14();
// ? func_80052A90();
// ? func_80052B34();
// ? func_80052B38();
// ? func_80052BE0();
// ? func_80052C98();
// ? func_80052EBC();
// ? func_80052EC0();
// ? func_80052F50();
// ? func_80053254();
// ? func_800533F4();
// ? func_800533F8();
// ? func_80053488();
// ? func_80053534();
// ? func_80053644();
// ? func_80053648();
// ? func_800536D0();
// ? func_80053968();
// ? func_80053A4C();
// ? func_80053A50();
// ? func_80053C70();
// ? func_80053D98();
// ? func_80053F04();
// ? func_80053F08();
// ? func_80053F0C();
// ? func_80053F10();
// ? func_8005402C();
// ? func_80054030();
// ? func_80054158();
// ? func_80054800();
// ? func_800549A8();
// ? func_800549AC();
// ? func_80054A1C();
// ? func_80054B84();
// ? func_80054CD4();
// ? func_80054CD8();
// ? func_80054CDC();
// ? func_80054CE0();
// ? func_80054E00();

void monkey_sprite_draw(struct Sprite *);
int u_get_monkey_bitmap_id(int, int, int);
// ? func_80081D34();
// ? func_80081D64();
// ? func_80081D90();
// ? func_80081DBC();
// ? func_80081DEC();
// ? func_80081E1C();
// ? func_80081E4C();
// ? func_80081E58();
// ? func_80081E84();
// ? func_80081EB4();
// ? func_80081EC4();
// ? func_80081EF0();
// ? func_80081F20();
void func_80081F30(void);
void func_80082024(int, struct Sprite *);
// ? func_80082C6C();
// ? func_80083138();
void ev_minimap_init(void);
void ev_minimap_main(void);
void ev_minimap_dest(void);
void func_800846B0(int);
void func_80084794(void *);
void minimap_change_size(void);
// ? func_800847FC();
void minimap_draw(void);

// ? func_80085C0C();
// ? draw_aiai_hair();
void func_80085DB0(struct Ape *);
// ? draw_eye();
// ? draw_baby_hand();
// ? draw_left_hand();
// ? draw_right_hand();
// ? func_800862F4();
// ? func_8008638C();
// ? func_80086434();
// ? func_80086538();
// ? draw_baby_head();
// ? func_8008669C();
// ? draw_head();
// ? draw_ear();
// ? func_800870EC();
// ? func_800874B0();
// ? func_80087B10();
void func_80088230(int arg0, int arg1, int arg2, struct Struct802B37F0_sub2_child *arg3);
void func_800885EC(void);
void func_800886E0(int);
void func_8008897C(int);
void func_80088A10(void);
// ? func_80088AF4();
int func_80088C18(void);
void func_80088C28(void);
// ? func_80088D44();
void func_80088E90(void);
void func_80088F18(void);
void func_80088FD4(int);
// ? func_800890D4();
// ? func_8008923C();

// code_2.c
float func_8008CDC0(float, struct Struct80176434 *);
void func_8008CF00(struct Struct8008CF00 *arg0, int arg1);
void func_8008D158(u32 arg0);
int func_8008D1DC(void (*)(struct Ape *, int), struct Ape *, int);
void func_8008D240(void);
void func_8008D29C(int);
void func_8008D330(struct NlModel *arg0, u32 arg1, u32 arg2);
void func_8008D36C(struct NlModel *arg0, u32 arg1, u32 arg2);
void func_8008D3A8(struct NlModel *arg0, u32 arg1, u32 arg2);

int lzs_decompress(u8 *, void *);
// ? func_8008D6BC();
// ? set_tev_material_ambient_colors();
void avdisp_init(void);
// ? u_avdisp_alloc_matrix_lists();
// ? func_8008D6D4();
void func_8008D788(void);
void *u_avdisp_alloc_matrix_lists(int count);
// ? u_get_stitching_model_mtx();
// ? load_model();
// ? free_model();
struct GMA *load_gma(char *fileName, struct TPL *tpl);
struct GMA *load_gma_from_aram(u32 aramSrc, u32 size, struct TPL *tpl);
void free_gma(struct GMA *gma);
struct TPL *load_tpl(char *fileName);
struct TPL *load_tpl_from_aram(u32 aramSrc, u32 size);
GXTexObj *create_tpl_tex_objs(struct TPL *tpl);
void free_tpl(struct TPL *tpl);
void avdisp_set_bound_sphere_scale(float);
void avdisp_set_ambient(float, float, float);
void avdisp_draw_model_culled_sort_translucent(struct GMAModel *);
void avdisp_draw_model_culled_sort_none(struct GMAModel *);
void avdisp_draw_model_culled_sort_all();
void avdisp_set_alpha(float alpha);
void avdisp_set_light_mask(u32 lightMask);
void avdisp_set_inf_light_dir(Vec *a);
void avdisp_set_inf_light_color(float, float, float);
void avdisp_set_z_mode(GXBool compareEnable, GXCompare compareFunc, GXBool updateEnable);
BallEnvFunc u_avdisp_set_some_func_1(BallEnvFunc);
Func802F20F0 u_avdisp_set_some_func_2(Func802F20F0);
// ? func_8008E5F8();
// ? func_8008E64C();
// ? set_shape_flags_in_model();
void avdisp_draw_model_unculled_sort_translucent(struct GMAModel *a);
// ? skip_mesh();
void avdisp_draw_model_unculled_sort_none(struct GMAModel *a);
void avdisp_draw_model_unculled_sort_all(struct GMAModel *a);
// ? u_avdisp_draw_model_4();
int get_texture_max_lod(int width, int height);
// ? init_material();
GXTexObj *init_model(struct GMAModel *a, struct TPL *b, GXTexObj *c);
void u_iteratively_multiply_model_matrices(struct GMAModel *a);
void draw_shape_deferred_callback(struct DrawShapeDeferredNode *a);
u32 avdisp_enable_custom_tex_mtx(u32);
void avdisp_set_custom_tex_mtx(int unused, Mtx mtx);
void avdisp_set_post_mult_color(float, float, float, float);
void avdisp_set_post_add_color(float, float, float, float);
void avdisp_enable_fog(int a);
void avdisp_set_fog_params(int, float, float);
void avdisp_set_fog_color(u8 a, u8 b, u8 c);
void u_set_transform_matrices(u8 *a);
struct GMAShape *draw_shape(struct GMAModel *model, struct GMAShape *mesh, struct GMATevLayer *c);
// ? func_8008FBB0();
// ? draw_shape_reflection_maybe();
void draw_indexed_model(struct GMAModel *model, struct GMAShape *b, struct GMATevLayer *mtrl);
void init_tev_material_cache(struct GMAModel *model, struct GMAShape *b);
// ? u_compute_texmtx0();
// ? u_compute_texmtx1and2();
void init_some_texture(void);
void build_post_multiply_tev_stage(GXTevStageID a);
void build_post_add_tev_stage(GXTevStageID a);
void build_diffuse_layer_uncached(struct TevStageInfo *a, GXTevColorArg colorArg, GXTevAlphaArg alphaArg, GXTexGenSrc texGenSrc);
void build_diffuse_layer_cached(struct TevStageInfo *a, GXTevColorArg colorArg, GXTevAlphaArg alphaArg);
void diffuse_layer_next(struct TevStageInfo *a);
void build_alpha_blend_layer_uncached(struct TevStageInfo *a, GXTevColorArg colorArg, GXTevAlphaArg alphaArg, GXTexGenSrc texGenSrc);
void build_alpha_blend_layer_cached(struct TevStageInfo *a, GXTevColorArg colorArg, GXTevAlphaArg alphaArg);
void alpha_blend_layer_next(struct TevStageInfo *a);
void build_view_specular_layer_uncached(struct TevStageInfo *a, GXTevColorArg colorArg, GXTevAlphaArg alphaArg, u32 d);
void build_view_specular_layer_cached(struct TevStageInfo *a, GXTevColorArg colorArg, GXTevAlphaArg alphaArg);
void view_specular_layer_next(struct TevStageInfo *a);
void build_world_specular_layer_uncached(struct TevStageInfo *a, GXTevColorArg colorArg, GXTevAlphaArg alphaArg, u32 d);
void build_world_specular_layer_cached(struct TevStageInfo *a, GXTevColorArg colorArg, GXTevAlphaArg alphaArg);
void world_specular_layer_next(struct TevStageInfo *a);
void build_unk3_layer_uncached(struct TevStageInfo *a, GXTevColorArg colorArg, GXTevAlphaArg alphaArg, GXTexGenSrc texGenSrc);
void build_unk3_layer_cached(struct TevStageInfo *a, GXTevColorArg colorArg, GXTevAlphaArg alphaArg);
void unk3_layer_next(struct TevStageInfo *a);

void func_80092498(void);
void func_800924CC(void);
void shadowerase_main(void);
void u_init_shadow_stuff_probably(struct Struct80092B98 *);
int func_80092D34(void);
void u_draw_ball_shadow(void);
void func_80092F90(void *);
// ? func_800934B0();
// ? func_80093920();
void mode_mini_func(void);
void func_80093A84(void (*)(void), void (*)(void), int, int);
void submode_mini_game_init_func(void);
void submode_mini_game_main_func(void);
void u_minigame_draw(void);
void func_80093B84(void);
// ? func_80093BB4();
void submode_mini_select_init_func(void);
void submode_mini_select_main_func(void);
void submode_mini_test0_init_func(void);
void submode_mini_test0_main_func(void);
void func_80093E28(void);
void submode_mini_ending_init_func(void);
void submode_mini_ending_main_func(void);
void func_80094028(void);
void func_800940B8(void);
void func_800940E0(void);
void u_something_with_lens_flare_2();
void u_something_with_lens_flare_1();
void func_800946BC(Vec *);
void func_800946DC(int, int);
void func_80094748(float);
void func_80094750(int);
void func_800947B0(void);
int func_800947F8(void);
void func_80094840(void);
void *func_80094870(void);
void func_800948D0(void *);
void func_800948F4(void);
void func_80094914(void);
void func_8009492C(struct Struct8009492C *);
void func_80094A34(void);

void submode_mini_commend_init_func(void);
void submode_mini_commend_main_func(void);
void func_8009BEF8(void);
// ? func_8009BF74();
// ? func_8009C178();
// ? func_8009C5E4();
// ? func_8009CAE0();
// ? func_8009CC34();
// ? func_8009CD5C();
int func_8009D5D8(void);
// ? func_8009D5F4();
// ? func_8009D794();
int func_8009D7CC(void);
int func_8009D7E8(void);
void func_8009D7FC(int, Vec *);
void func_8009D98C(Vec *);
// ? func_8009DB40();
void func_8009DB6C(Mtx);
// ? func_8009DBB0();
void func_8009F49C(int);
int memcard_is_write_in_progress(void);
u8 func_8009F4C4(void);
// ? init_gamedata_file();
// ? init_replay_file_data();
// ? probe_memcard();
// ? mount_memcard();
// ? check_mount_memcard_result();
// ? verify_filesystem();
// ? check_verify_filesystem_result();
// ? open_memcard_file();
// ? check_card_free_space();
// ? create_memcard_file();
// ? check_create_memcard_file_result();
// ? write_memcard_file();
// ? check_write_memcard_file_result();
// ? set_memcard_file_metadata();
// ? check_set_memcard_file_metadata_result();
// ? read_memcard_file();
// ? check_read_memcard_file_result();
// ? get_memcard_file_metadata();
// ? format_memcard();
// ? check_format_memcard_result();
// ? get_memcard_file_metadata_2();
// ? replay_list_open_and_read();
// ? open_replay_file();
// ? delete_memcard_file();
// ? check_delete_memcard_file_result();
// ? delete_gamedata_file();
// ? check_delete_gamedata_file_result();
// ? rename_gamedata_file();
// ? check_rename_gamedata_file_result();
// ? load_sequence();
// ? save_sequence();
// ? replay_save_sequence();
// ? replay_list_sequence();
// ? replay_load_sequence();
void memcard_init(void);
void ev_memcard_init(void);
void ev_memcard_main(void);
void ev_memcard_dest(void);
// ? draw_memcard_msg();
void memcard_draw_ui(void);
void func_800A4CEC(void);
void func_800A4E70();
void func_800A4F04(void);
// ? DEMOInitCaption();
// ? DEMOInitROMFont();
// ? DEMOSetROMFontSize();
// ? DrawFontChar();
// ? DEMORFPuts();
// ? DEMORFPrintf();
// ? DEMOGetRFTextWidth();
void func_800A5704(void);
void ev_view_init(void);
void ev_view_main(void);
void ev_view_dest(void);
void view_draw(void);
void func_800A5F28(void);
void view_create_text_sprites(void);
void view_destroy_text_sprites(void);
void view_init_stage_anim(void);
void view_animate_stage(void);
void func_800A66CC(void);
void func_800A66E4(void);
void func_800A66FC(void);
void func_800A671C(void);
void draw_items(void);
void draw_banana_shadows(void);
void draw_stage_geometry(void);
void draw_stage_objects(void);
void get_curr_stage_view_bounds(struct Sphere *);
void view_apply_camera(struct Camera *);
void submode_mini_ranking_init_func(void);
void submode_mini_ranking_main_func(void);
// ? func_800A7A8C();
// ? func_800A7B7C();
// ? func_800A82D0();
// ? func_800A83C4();
// ? func_800A85F8();
// ? func_800A8828();
// ? func_800A8C44();
// ? func_800A8FCC();
// ? func_800A916C();
// ? func_800AADC4();
// ? func_800AAE80();
// ? func_800AAF40();
// ? func_800AB174();
// ? func_800AB2A0();
// ? func_800AB444();
// ? func_800AB720();
// ? func_800AB830();
// ? func_800AB8D8();
// ? func_800AB974();
// ? func_800ABA10();
// ? func_800ABAE0();
// ? func_800ABCF4();
// ? func_800ABE80();
// ? func_800AC064();
// ? func_800AC248();
// ? func_800AC43C();

void func_800ACA40(void);
int u_read_dvd_file(DVDFileInfo *file, void *arg1, u32 arg2, int arg3);
void init_loading_gct(void);

void func_800AD180(struct Preview *, int, int, float, float, float, float, float);
void func_800AD38C(void);
void ev_name_entry_init(void);
void ev_name_entry_main(void);
void ev_name_entry_dest(void);
void func_800AE408(void);
int u_is_name_entry_finished(void);
// ? func_800AE8D0();
// ? func_800AE930();
void func_800AEAD0(void);
// ? func_800AEB28();
// ? func_800AEBA8();
void *func_800AEC74(int, int);
int func_800AECCC(int, void *);
// ? func_800AED54();
void func_800AEDDC(void);
void func_800AEDE0(void);
// ? func_800AF098();
void func_800AF164(void);
// ? func_800AF1DC();
// ? func_800AF1F8();
// ? func_800AF2C8();
// ? func_800AF3A4();
// ? func_800AF3B0();
// ? func_800AF3DC();
// ? func_800AF478();
// ? func_800AF62C();
// ? func_800AF6D4();
void stobj_nameent_btn_init(struct Stobj *);
void stobj_nameent_btn_main(struct Stobj *);
void stobj_nameent_btn_draw(struct Stobj *);
void stobj_nameent_btn_coli(struct Stobj *, struct PhysicsBall *);
void stobj_nameent_btn_destroy(struct Stobj *);
void stobj_nameent_btn_debug(struct Stobj *);
void func_800AFC1C();
void func_800AFC4C();
void credits_finish(void);
void credits_init(void);
void credits_main(void);
// ? func_800B0B48();
// ? func_800B340C();
// ? func_800B34B4();
// ? func_800B361C();
// ? func_800B3784();
// ? func_800B38EC();
// ? func_800B3CC8();
// ? func_800B3DCC();
// ? func_800B3ECC();
// ? func_800B42EC();
// ? func_800B4710();
// ? func_800B4A50();
// ? func_800B5020();
// ? func_800B55E4();
// ? func_800B5B5C();
// ? func_800B5C54();
void ev_vibration_init(void);
void ev_vibration_main(void);
void ev_vibration_dest(void);
void func_800B60F4(int, int, int);
// ? func_800B6224();
// ? func_800B622C();
void func_800B6234(void);
int func_800B62FC(void);
void func_800B6430(void);
void func_800B64B0(void);
// ? func_800B65B4();
// ? func_800B6608();
// ? func_800B6848();
// ? func_800B69F8();
// ? func_800B6C14();
// ? func_800B6EA4();
// ? func_800B6F9C();
// ? func_800B7078();
// ? func_800B72D4();
// ? func_800B7B6C();
// ? func_800B7D38();
// ? func_800B7F6C();
// ? func_800B7FB4();
// ? func_800B83EC();
// ? func_800B86E0();
// ? func_800B8780();
// ? func_800B8AA4();
// ? func_800B8D7C();
// ? func_800B8E1C();
// ? func_800B9444();
// ? func_800B9724();
// ? func_800B9920();
// ? func_800B9A8C();
// ? func_800B9EA4();
// ? func_800B9FDC();
// ? func_800BA124();
// ? func_800BA160();
// ? func_800BA4F4();
// ? func_800BA51C();
// ? func_800BA928();
// ? func_800BA950();
// ? func_800BB050();
// ? func_800BB064();
// ? func_800BB068();
// ? func_800BB084();
// ? func_800BBA54();
// ? func_800BBA58();
// ? func_800BBB10();
// ? func_800BBB78();
// ? func_800BBBA8();
// ? func_800BC820();
// ? func_800BC8B8();
// ? func_800BCE54();
// ? func_800BD470();
// ? func_800BD4B8();
// ? func_800BEEE8();
// ? func_800BF2D0();
// ? func_800BF2D4();
// ? func_800BF4F4();
// ? func_800BF658();
// ? func_800BF774();
// ? func_800BF8C4();
// ? func_800BF948();
// ? func_800BF9CC();
// ? func_800BFA2C();
// ? func_800BFC2C();
// ? func_800C008C();
// ? func_800C00F0();
// ? func_800C013C();
// ? func_800C0354();
// ? func_800C09B0();
// ? func_800C09B4();
// ? func_800C09B8();
// ? func_800C09D0();
// ? func_800C0C1C();
// ? func_800C0DBC();
// ? func_800C0DC0();
// ? func_800C0F94();
// ? func_800C122C();
// ? func_800C1418();

// mkbe.sel_stage.rel functions
void create_sel_stage_sprites(void);
void dummy_func_C90(void);
void dummy_func_C94(void);
void dummy_func_C98(void);
void sel_stage_draw(void);

// ? PPCMfmsr();
// ? PPCMtmsr();
// ? PPCMfhid0();
// ? PPCMfl2cr();
// ? PPCMtl2cr();
// ? PPCMtdec();
// ? PPCSync();
// ? PPCHalt();
// ? PPCMtmmcr0();
// ? PPCMtmmcr1();
// ? PPCMfpmc1();
// ? PPCMtpmc1();
// ? PPCMtpmc2();
// ? PPCMfpmc3();
// ? PPCMtpmc3();
// ? PPCMfpmc4();
// ? PPCMtpmc4();
// ? PPCMfhid2();
// ? PPCMthid2();
// ? PPCMtwpar();
// ? OSGetConsoleType();
// ? OSInit();
// ? OSExceptionInit();
// ? __OSDBINITSTART();
// ? __OSDBJUMPSTART();
// ? __OSDBJUMPEND();
// ? __OSGetExceptionHandler();
// ? __OSEVStart();
// ? __OSEVEnd();
// ? OSDefaultExceptionHandler();
// ? __OSPSInit();
// ? __OSGetDIConfig();
// ? OSInitAlarm();
// ? OSCreateAlarm();
// ? InsertAlarm();
// ? OSSetAlarm();
// ? OSSetAbsAlarm();
// ? OSSetPeriodicAlarm();
// ? OSCancelAlarm();
// ? DecrementerExceptionCallback();
// ? DecrementerExceptionHandler();
// ? DLInsert();
// ? OSAllocFromHeap();
// ? OSFreeToHeap();
// ? OSSetCurrentHeap();
// ? OSInitAlloc();
// ? OSCreateHeap();
// ? OSCheckHeap();
// ? OSGetArenaHi();
// ? OSGetArenaLo();
// ? OSSetArenaHi();
// ? OSSetArenaLo();
// ? __OSInitAudioSystem();
// ? __OSStopAudioSystem();
// ? DCEnable();
// ? DCInvalidateRange();
// ? DCFlushRange();
// ? DCStoreRange();
// ? DCFlushRangeNoSync();
// ? DCZeroRange();
// ? ICInvalidateRange();
// ? ICFlashInvalidate();
// ? ICEnable();
// ? __LCEnable();
// ? LCEnable();
// ? L2GlobalInvalidate();
// ? DMAErrorHandler();
// ? __OSCacheInit();
// ? __OSLoadFPUContext();
// ? __OSSaveFPUContext();
// ? OSSetCurrentContext();
// ? OSGetCurrentContext();
// ? OSSaveContext();
// ? OSLoadContext();
// ? OSGetStackPointer();
// ? OSClearContext();
// ? OSDumpContext();
// ? OSSwitchFPUContext();
// ? __OSContextInit();
// ? OSReport();
// ? OSPanic();
// ? OSSetErrorHandler();
// ? __OSUnhandledException();
// ? SetExiInterruptMask();
// ? EXIImm();
// ? EXIImmEx();
// ? EXIDma();
// ? EXISync();
// ? EXIClearInterrupts();
// ? EXISetExiCallback();
// ? __EXIProbe();
// ? EXIProbeEx();
// ? EXIAttach();
// ? EXIDetach();
// ? EXISelect();
// ? EXIDeselect();
// ? EXIInterruptHandler();
// ? TCInterruptHandler();
// ? EXTInterruptHandler();
// ? EXIInit();
// ? EXILock();
// ? EXIUnlock();
// ? EXIGetStage();
// ? EXIGetID();
// ? GetFontCode();
// ? Decode();
// ? OSGetFontEncode();
// ? ReadROM();
// ? ExpandFontSheet();
// ? OSInitFont();
// ? OSGetFontTexture();
// ? OSGetFontWidth();
// ? OSDisableInterrupts();
// ? OSEnableInterrupts();
// ? OSRestoreInterrupts();
// ? __OSSetInterruptHandler();
// ? __OSGetInterruptHandler();
// ? __OSInterruptInit();
// ? SetInterruptMask();
// ? __OSMaskInterrupts();
// ? __OSUnmaskInterrupts();
// ? __OSDispatchInterrupt();
// ? ExternalInterruptHandler();
// ? func_800C68DC();
// ? OSNotifyLink();
// ? OSSetStringTable();
// ? Relocate();
// ? OSLink();
// ? Undo();
// ? OSUnlink();
// ? __OSModuleInit();
// ? OSGetPhysicalMemSize();
// ? __OSUnlockAllMutex();
// ? Run();
// ? Callback();
// ? __OSReboot();
// ? OSRegisterResetFunction();
// ? Reset();
// ? __OSDoHotReset();
// ? OSResetSystem();
// ? __OSResetSWInterruptHandler();
// ? OSGetResetButtonState();
// ? WriteSramCallback();
// ? WriteSram();
// ? __OSInitSram();
// ? __OSLockSram();
// ? __OSLockSramEx();
// ? UnlockSram();
// ? __OSUnlockSram();
// ? __OSUnlockSramEx();
// ? __OSSyncSram();
// ? __OSReadRom();
// ? OSGetSoundMode();
// ? OSSetSoundMode();
// ? SIBusy();
// ? CompleteTransfer();
// ? SIInterruptHandler();
// ? SIInit();
// ? __SITransfer();
// ? SIGetCommand();
// ? SISetCommand();
// ? SITransferCommands();
// ? SISetXY();
// ? SIEnablePolling();
// ? SIDisablePolling();
// ? SIGetResponse();
// ? AlarmHandler();
// ? SITransfer();
// ? __OSSystemCallVectorStart();
// ? __OSSystemCallVectorEnd();
// ? __OSInitSystemCall();
// ? __OSThreadInit();
// ? OSInitThreadQueue();
// ? OSGetCurrentThread();
// ? OSDisableScheduler();
// ? OSEnableScheduler();
// ? UnsetRun();
// ? __OSGetEffectivePriority();
// ? SetEffectivePriority();
// ? SelectThread();
// ? __OSReschedule();
// ? OSCancelThread();
// ? OSResumeThread();
// ? OSSuspendThread();
// ? OSSleepThread();
// ? OSWakeupThread();
// ? OSGetTime();
// ? OSGetTick();
// ? __OSGetSystemTime();
// ? GetDates();
// ? OSTicksToCalendarTime();
// ? InitializeUART();
// ? ReadUARTN();
// ? WriteUARTN();
// ? __init_user();
// ? __init_cpp();
// ? _ExitProcess();
// ? DBInit();
// ? __DBExceptionDestinationAux();
// ? __DBExceptionDestination();
// ? __DBIsExceptionMarked();
// ? DBPrintf();
// ? PSMTXIdentity();
// ? C_MTXScale();
// ? C_MTXQuat();
// ? C_MTXLookAt();
// ? C_MTXFrustum();
// ? C_MTXPerspective();
// ? C_MTXOrtho();
// ? PSVECNormalize();
// ? PSVECCrossProduct();
// ? __DVDInitWA();
// ? __DVDInterruptHandler();
// ? AlarmHandler_2();
// ? AlarmHandlerForTimeout();
// ? Read();
// ? SeekTwiceBeforeRead();
// ? DVDLowRead();
// ? DVDLowSeek();
// ? DVDLowWaitCoverClose();
// ? DVDLowReadDiskID();
// ? DVDLowStopMotor();
// ? DVDLowRequestError();
// ? DVDLowInquiry();
// ? DVDLowAudioStream();
// ? DVDLowRequestAudioStatus();
// ? DVDLowAudioBufferConfig();
// ? DVDLowReset();
// ? DVDLowBreak();
// ? DVDLowClearCallback();
// ? __DVDLowSetWAType();
// ? __DVDFSInit();
// ? DVDConvertPathToEntrynum();
// ? DVDFastOpen();
// ? DVDOpen();
// ? DVDClose();
// ? entryToPath();
// ? DVDGetCurrentDir();
// ? DVDChangeDir();
// ? DVDReadAsyncPrio();
// ? cbForReadAsync();
// ? DVDOpenDir();
// ? DVDReadDir();
// ? DVDCloseDir();
// ? DVDPrepareStreamAsync();
// ? cbForPrepareStreamAsync();
// ? DVDInit();
// ? stateReadingFST();
// ? cbForStateReadingFST();
// ? cbForStateError();
// ? stateTimeout();
// ? stateGettingError();
// ? CategorizeError();
// ? cbForStateGettingError();
// ? cbForUnrecoveredError();
// ? cbForUnrecoveredErrorRetry();
// ? stateGoToRetry();
// ? cbForStateGoToRetry();
// ? stateCheckID();
// ? stateCheckID3();
// ? stateCheckID2();
// ? cbForStateCheckID1();
// ? cbForStateCheckID2();
// ? cbForStateCheckID3();
// ? AlarmHandler_3();
// ? stateCoverClosed();
// ? stateCoverClosed_CMD();
// ? cbForStateCoverClosed();
// ? stateMotorStopeped();
// ? cbForStateMotorStopped();
// ? stateReady();
// ? stateBusy();
// ? cbForStateBusy();
// ? DVDReadAbsAsyncPrio();
// ? DVDReadAbsAsyncForBS();
// ? DVDReadDiskID();
// ? DVDPrepareStreamAbsAsync();
// ? DVDCancelStreamAsync();
// ? DVDStopStreamAtEndAsync();
// ? DVDGetStreamErrorStatusAsync();
// ? DVDGetStreamPlayAddrAsync();
// ? DVDReset();
// ? DVDGetDriveStatus();
// ? DVDCancelAsync();
// ? DVDCancel();
// ? cbForCancelSync();
// ? DVDGetCurrentDiskID();
// ? DVDCheckDisk();
// ? __DVDPrepareResetAsync();
// ? __DVDClearWaitingQueue();
// ? __DVDPushWaitingQueue();
// ? __DVDPopWaitingQueue();
// ? __DVDCheckWaitingQueue();
// ? __DVDDequeueWaitingQueue();
// ? __DVDStoreErrorCode();
// ? cb();
// ? __fstLoad();
// ? __VIRetraceHandler();
// ? getTiming();
// ? func_800CF02C();
// ? func_800CF034();
// ? func_800CF03C();
// ? func_800CF044();
// ? func_800CF04C();
// ? func_800CF054();
// ? __VIInit();
// ? VIInit();
// ? VIWaitForRetrace();
// ? setFbbRegs();
// ? setVerticalRegs();
// ? VIConfigure();
// ? VIFlush();
// ? VISetNextFrameBuffer();
// ? VISetBlack();
// ? getCurrentFieldEvenOdd();
// ? VIGetNextField();
// ? VIGetTvFormat();
// ? DoReset();
// ? PADProbeCallback();
// ? UpdateOrigin();
// ? PADOriginCallback();
// ? PADOriginUpdateCallback();
// ? PADFixCallback();
// ? PADResetCallback();
// ? PADReset();
// ? PADRecalibrate();
// ? PADInit();
// ? PADReceiveCheckCallback();
// ? PADRead();
// ? PADSetSamplingRate();
// ? PADControlAllMotors();
// ? PADControlMotor();
// ? PADSetSpec();
// ? SPEC0_MakeStatus();
// ? SPEC1_MakeStatus();
// ? SPEC2_MakeStatus();
// ? PADSetAnalogMode();
// ? func_800D27C8();
// ? AIRegisterDMACallback();
// ? AIInitDMA();
// ? AIStartDMA();
// ? AIRegisterStreamCallback();
// ? AIGetStreamSampleCount();
// ? AIResetStreamSampleCount();
// ? AISetStreamTrigger();
// ? AISetStreamPlayState();
// ? AIGetStreamPlayState();
// ? AISetDSPSampleRate();
// ? AIGetDSPSampleRate();
// ? AISetStreamSampleRate();
// ? __AI_set_stream_sample_rate();
// ? AIGetStreamSampleRate();
// ? AISetStreamVolLeft();
// ? AIGetStreamVolLeft();
// ? AISetStreamVolRight();
// ? AIGetStreamVolRight();
// ? AIInit();
// ? __AISHandler();
// ? __AIDHandler();
// ? __AICallbackStackSwitch();
// ? __AI_SRC_INIT();
// ? ARRegisterDMACallback();
// ? ARGetDMAStatus();
// ? ARStartDMA();
// ? ARInit();
// ? ARGetBaseAddress();
// ? ARGetSize();
// ? __ARHandler();
// ? __ARChecksize();
// ? __ARQServiceQueueLo();
// ? __ARQCallbackHack();
// ? __ARQInterruptServiceRoutine();
// ? ARQInit();
// ? ARQPostRequest();
// ? DSPCheckMailToDSP();
// ? DSPCheckMailFromDSP();
// ? DSPReadMailFromDSP();
// ? DSPSendMailToDSP();
// ? DSPInit();
// ? DSPAddTask();
// ? __DSP_debug_printf();
// ? __DSPHandler();
// ? __DSP_exec_task();
// ? __DSP_boot_task();
// ? __DSP_insert_task();
// ? __DSP_remove_task();
// ? __CARDDefaultApiCallback();
// ? __CARDSyncCallback();
// ? __CARDExtHandler();
// ? __CARDExiHandler();
// ? __CARDTxHandler();
// ? __CARDUnlockedHandler();
// ? __CARDReadNintendoID();
// ? __CARDEnableInterrupt();
// ? __CARDReadStatus();
// ? __CARDClearStatus();
// ? TimeoutHandler();
// ? Retry();
// ? UnlockedCallback();
// ? __CARDStart();
// ? __CARDReadSegment();
// ? __CARDWritePage();
// ? __CARDEraseSector();
// ? CARDInit();
// ? __CARDSetDiskID();
// ? __CARDGetControlBlock();
// ? __CARDPutControlBlock();
// ? CARDGetResultCode();
// ? CARDFreeBlocks();
// ? __CARDSync();
// ? func_800D64B8();
// ? bitrev();
// ? ReadArrayUnlock();
// ? DummyLen();
// ? __CARDUnlock();
// ? InitCallback();
// ? DoneCallback();
// ? BlockReadCallback();
// ? __CARDRead();
// ? BlockWriteCallback();
// ? __CARDWrite();
// ? __CARDGetFatBlock();
// ? WriteCallback();
// ? EraseCallback();
// ? __CARDAllocBlock();
// ? __CARDFreeBlock();
// ? __CARDUpdateFatBlock();
// ? __CARDGetDirBlock();
// ? WriteCallback_2();
// ? EraseCallback_2();
// ? __CARDUpdateDir();
// ? __CARDUpdateSum();
// ? VerifyID();
// ? VerifyDir();
// ? VerifyFAT();
// ? __CARDVerify();
// ? CARDCheckExAsync();
// ? CARDCheckAsync();
// ? CARDProbeEx();
// ? DoMount();
// ? __CARDMountCallback();
// ? CARDMountAsync();
// ? CARDMount();
// ? DoUnmount();
// ? CARDUnmount();
// ? FormatCallback();
// ? __CARDFormatRegionAsync();
// ? __CARDCompareFileName();
// ? __CARDAccess();
// ? __CARDIsPublic();
// ? __CARDGetFileNo();
// ? CARDFastOpen();
// ? CARDOpen();
// ? CARDClose();
// ? __CARDIsOpened();
// ? CreateCallbackFat();
// ? CARDCreateAsync();
// ? __CARDSeek();
// ? ReadCallback();
// ? CARDReadAsync();
// ? CARDCancel();
// ? WriteCallback_3();
// ? EraseCallback_3();
// ? CARDWriteAsync();
// ? DeleteCallback();
// ? CARDFastDeleteAsync();
// ? CARDDeleteAsync();
// ? CARDDelete();
// ? UpdateIconOffsets();
// ? CARDGetStatus();
// ? CARDSetStatusAsync();
// ? CARDRenameAsync();
// ? CARDRename();
// ? HIOReadMailbox();
// ? HIOWriteMailbox();
// ? HIORead();
// ? HIOWrite();
// ? __GXDefaultTexRegionCallback();
// ? __GXDefaultTlutRegionCallback();
// ? GXInit();
// ? GXCPInterruptHandler();
// ? GXInitFifoBase();
// ? GXInitFifoPtrs();
// ? GXInitFifoLimits();
// ? GXSetCPUFifo();
// ? GXSetGPFifo();
// ? GXSaveCPUFifo();
// ? __GXSaveCPUFifoAux();
// ? GXGetGPStatus();
// ? GXGetFifoPtrs();
// ? __GXFifoInit();
// ? __GXFifoReadEnable();
// ? __GXFifoReadDisable();
// ? __GXFifoLink();
// ? __GXWriteFifoIntEnable();
// ? __GXWriteFifoIntReset();
// ? GXGetCPUFifo();
// ? GXGetGPFifo();
// ? __GXXfVtxSpecs();
// ? GXSetVtxDesc();
// ? GXSetVtxDescv();
// ? __GXSetVCD();
// ? GXGetVtxDesc();
// ? GXGetVtxDescv();
// ? GXClearVtxDesc();
// ? GXSetVtxAttrFmt();
// ? GXSetVtxAttrFmtv();
// ? __GXSetVAT();
// ? GXGetVtxAttrFmt();
// ? func_800DEB2C();
// ? func_800DEB70();
// ? func_800DEB94();
// ? func_800DEBB8();
// ? func_800DEBE0();
// ? func_800DEC08();
// ? func_800DEC30();
// ? func_800DEC58();
// ? func_800DEC80();
// ? func_800DECA8();
// ? func_800DECD0();
// ? GXGetVtxAttrFmtv();
// ? GXInvalidateVtxCache();
// ? GXSetTexCoordGen2();
// ? GXSetNumTexGens();
// ? GXFlush();
// ? GXSetDrawSync();
// ? GXSetDrawDone();
// ? GXDrawDone();
// ? GXPokeAlphaMode();
// ? GXPokeAlphaRead();
// ? GXPokeAlphaUpdate();
// ? GXPokeBlendMode();
// ? GXPokeColorUpdate();
// ? GXPokeDstAlpha();
// ? GXPokeDither();
// ? GXPokeZMode();
// ? GXSetDrawSyncCallback();
// ? GXTokenInterruptHandler();
// ? GXSetDrawDoneCallback();
// ? GXFinishInterruptHandler();
// ? __GXPEInit();
void __GXSetDirtyState(void);
// ? GXBegin();
// ? __GXSendFlushPrim();
// ? GXSetLineWidth();
// ? GXSetPointSize();
// ? GXEnableTexOffsets();
// ? GXSetCullMode();
// ? GXSetCoPlanar();
// ? __GXSetGenMode();
// ? GXAdjustForOverscan();
// ? GXSetDispCopySrc();
// ? GXSetTexCopySrc();
// ? GXSetDispCopyDst();
// ? GXSetTexCopyDst();
// ? GXSetDispCopyFrame2Field();
// ? GXSetCopyClamp();
// ? GXSetDispCopyYScale();
// ? GXSetCopyClear();
// ? GXSetCopyFilter();
// ? GXSetDispCopyGamma();
// ? GXCopyDisp();
// ? GXCopyTex();
// ? GXClearBoundingBox();
// ? GXInitLightAttnK();
// ? GXInitLightSpot();
// ? GXInitLightDistAttn();
// ? GXInitLightPos();
// ? GXGetLightPos();
// ? GXInitLightDir();
// ? GXInitLightColor();
// ? GXGetLightColor();
// ? GXLoadLightObjImm();
// ? GXSetChanAmbColor();
// ? GXSetChanMatColor();
// ? GXSetNumChans();
// ? GXSetChanCtrl();
// ? GXGetTexBufferSize();
// ? __GetImageTileCount();
// ? GXInitTexObj();
// ? GXInitTexObjLOD();
// ? GXInitTexObjWrapMode();
// ? GXGetTexObjData();
// ? GXGetTexObjWidth();
// ? GXGetTexObjHeight();
// ? GXGetTexObjFmt();
// ? GXGetTexObjWrapS();
// ? GXGetTexObjWrapT();
// ? GXGetTexObjMipMap();
// ? GXLoadTexObjPreLoaded();
// ? GXLoadTexObj();
// ? GXInitTexCacheRegion();
// ? GXInitTlutObj();
// ? GXInvalidateTexAll();
// ? GXSetTexRegionCallback();
// ? GXSetTlutRegionCallback();
// ? __SetSURegs();
// ? __GXSetSUTexSize();
// ? GXSetTevIndirect();
// ? GXSetIndTexMtx();
// ? GXSetIndTexCoordScale();
// ? GXSetIndTexOrder();
// ? GXSetNumIndStages();
// ? GXSetTevDirect();
// ? __GXUpdateBPMask();
// ? __GXFlushTextureState();


// ? GXDrawCylinder();
// ? GXDrawSphere();
// ? GXDrawCubeFace();
// ? GXDrawCube();
// ? __GXSetRange();
// ? GXBeginDisplayList();
// ? GXEndDisplayList();
// ? GXCallDisplayList();
// ? GXSetProjection();
// ? GXGetProjectionv();
// ? WriteMTXPS4x3();
// ? WriteMTXPS3x3from3x4();
// ? WriteMTXPS4x2();
// ? GXLoadPosMtxImm();
// ? GXLoadNrmMtxImm();
// ? GXSetCurrentMtx();
// ? GXLoadTexMtxImm();
// ? GXSetViewportJitter();
// ? GXSetViewport();
// ? GXSetScissor();
// ? GXSetScissorBoxOffset();
// ? GXSetClipMode();
// ? __GXSetMatrixIndex();
// ? GXClearGPMetric();
// ? GXInitXfRasMetric();
// ? GXReadXfRasMetric();
// ? PERFResetAllMemMetrics();
// ? PERFGetAllMemMetrics();
// ? PERFTokenCallback();
// ? PERFInit();
// ? PERFSetEvent();
// ? PERFStartFrame();
// ? PERFEndFrame();
// ? PERFEventStart();
// ? PERFEventEnd();
// ? PERFStartAutoSample();
// ? PERFEndAutoSample();
// ? PERFTimerCallback();
// ? PERFStartAutoSampling();
// ? PERFStopAutoSampling();
// ? __PERFDrawInit();
// ? PERFPreDraw();
// ? DrawBWBar();
// ? DrawKey();
// ? PERFDumpScreen();
// ? PERFPostDraw();
// ? PERFSetDrawBWBarKey();
// ? ResetNotes();
// ? AllocateNote();
// ? seqFreeKeyOffNote();
// ? GetPublicId();
// ? seqGetPrivateId();
// ? seqStartPlay();
// ? HandleMasterTrack();
// ? StartPause();
// ? seqPause();
// ? seqStop();
// ? seqKillInstancesByGroupID();
// ? seqSpeed();
// ? seqContinue();
// ? seqMute();
// ? seqVolume();
// ? seqCrossFade();
// ? GetStreamValue();
// ? GenerateNextTrackEvent();
// ? InsertGlobalEvent();
// ? HandleEvent();
// ? InitTrackEvents();
// ? InitTrackEventsSection();
// ? HandleTrackEvents();
// ? seqHandle();
// ? seqInit();
// ? synthSetBpm();
// ? synthGetTicksPerSecond();
// ? synthInitPortamento();
// ? do_voice_portamento();
// ? StartLayer();
// ? StartKeymap();
// ? synthStartSound();
// ? LowPrecisionHandler();
// ? ZeroOffsetHandler();
// ? EventHandler();
// ? synthAddJob();
// ? synthStartSynthJobHandling();
// ? synthForceLowPrecisionUpdate();
// ? synthKeyStateUpdate();
// ? HandleJobQueue();
// ? HandleFaderTermination();
// ? synthHandle();
// ? synthFXStart();
// ? synthFXSetCtrl();
// ? synthFXSetCtrl14();
// ? synthFXCloneMidiSetup();
// ? synthSendKeyOff();
// ? synthVolume();
// ? synthIsFadeOutActive();
// ? synthSetMusicVolumeType();
// ? synthHWMessageHandler();
// ? synthInit();
// ? sndSeqSpeed();
// ? sndSeqContinue();
// ? sndSeqMute();
// ? sndSeqVolume();
// ? seqGetMIDIPriority();
// ? sndFXCtrl();
// ? sndFXCtrl14();
// ? sndFXKeyOff();
// ? sndFXStartParaInfo();
// ? sndFXCheck();
// ? sndVolume();
// ? sndMasterVolume();
// ? sndOutputMode();
// ? sndSetAuxProcessingCallbacks();
// ? synthActivateStudio();
// ? synthDeactivateStudio();
// ? synthAddStudioInput();
// ? synthRemoveStudioInput();
// ? streamInit();
// ? streamHandle();
// ? streamCorrectLoops();
// ? streamKill();
// ? GetPrivateIndex();
// ? sndStreamAllocEx();
// ? sndStreamAllocLength();
// ? sndStreamFree();
// ? sndStreamActivate();
// ? sndStreamDeactivate();
// ? dataInsertKeymap();
// ? dataRemoveKeymap();
// ? dataInsertLayer();
// ? dataRemoveLayer();
// ? dataInsertCurve();
// ? dataRemoveCurve();
// ? dataInsertSDir();
// ? dataRemoveSDir();
// ? dataAddSampleReference();
// ? dataRemoveSampleReference();
// ? dataInsertFX();
// ? dataRemoveFX();
// ? dataInsertMacro();
// ? dataRemoveMacro();
// ? maccmp();
// ? dataGetMacro();
// ? smpcmp();
// ? dataGetSample();
// ? curvecmp();
// ? dataGetCurve();
// ? dataGetKeymap();
// ? layercmp();
// ? dataGetLayer();
// ? fxcmp();
// ? dataGetFX();
// ? dataInit();
// ? mcmdWait();
// ? mcmdLoop();
// ? mcmdPlayMacro();
// ? mcmdStartSample();
// ? mcmdVibrato();
// ? DoSetPitch();
// ? mcmdSetADSR();
// ? mcmdSetPitchADSR();
// ? DoPanningSetup();
// ? TranslateVolume();
// ? DoEnvelopeCalculation();
// ? mcmdRandomKey();
// ? SelectSource();
// ? mcmdPortamento();
// ? varGet32();
// ? varGet();
// ? varSet32();
// ? mcmdVarCalculation();
// ? mcmdSendMessage();
// ? mcmdSetKeyGroup();
// ? macHandleActive();
// ? def_800F421C();
// ? macHandle();
// ? macSampleEndNotify();
// ? macSetExternalKeyoff();
// ? macSetPedalState();
// ? TimeQueueAdd();
// ? UnYieldMacro();
// ? macMakeActive();
// ? macMakeInactive();
// ? macStart();
// ? macInit();
// ? vidInit();
// ? get_vidlist();
// ? vidRemoveVoiceReferences();
// ? vidMakeRoot();
// ? vidMakeNew();
// ? vidGetInternalId();
// ? voiceRemovePriority();
// ? voiceSetPriority();
// ? voiceAllocate();
// ? voiceFree();
// ? synthInitAllocationAids();
// ? voiceBlock();
// ? voiceUnblock();
// ? voiceKill();
// ? voiceKillSound();
// ? synthKillVoicesByMacroReferences();
// ? voiceIsLastStarted();
// ? voiceSetLastStarted();
// ? voiceResetLastStarted();
// ? voiceInitLastStarted();
// ? sndPitchUpOne();
// ? sndGetPitch();
// ? adsrConvertTimeCents();
// ? salChangeADSRState();
// ? adsrSetup();
// ? adsrStartRelease();
// ? adsrRelease();
// ? adsrHandle();
// ? adsrHandleLowPrecision();
// ? dataInitStack();
// ? InsertData();
// ? ScanIDList();
// ? ScanIDListReverse();
// ? sndPushGroup();
// ? sndPopGroup();
// ? seqPlaySong();
// ? sndSeqPlayEx();
// ? salInitDspCtrl();
// ? salInitHRTFBuffer();
// ? salActivateStudio();
// ? salDeactivateStudio();
// ? HandleDepopVoice();
// ? SortVoices();
// ? salBuildCommandList();
// ? salSynthSendMessage();
// ? salActivateVoice();
// ? salDeactivateVoice();
// ? salAddStudioInput();
// ? salRemoveStudioInput();
// ? salHandleAuxProcessing();
// ? salCalcVolume();
// ? UpdateRoomDistances();
// ? CheckRoomStatus();
// ? CheckDoorStatus();
// ? CalcEmitter();
// ? SetFXParameters();
// ? EmitterShutdown();
// ? s3dKillEmitterByFXID();
// ? AddRunningEmitter();
// ? AddStartingEmitter();
// ? StartContinousEmitters();
// ? s3dHandle();
// ? s3dInit();
// ? sndActive();
// ? salApplyMatrix();
// ? salNormalizeVector();
// ? inpSetGlobalMIDIDirtyFlag();
// ? inpSetMidiCtrl();
// ? inpSetMidiCtrl14();
// ? inpResetMidiCtrl();
// ? inpGetMidiCtrl();
// ? inpGetChannelDefaults();
// ? inpResetChannelDefaults();
// ? inpAddCtrl();
// ? inpFXCopyCtrl();
// ? inpSetMidiLastNote();
// ? inpGetMidiLastNote();
// ? inpSetMidiPortState();
// ? inpGetMidiPortState();
// ? _GetInputValue();
// ? inpGetVolume();
// ? inpGetPanning();
// ? inpGetSurPanning();
// ? inpGetPitchBend();
// ? inpGetDoppler();
// ? inpGetModulation();
// ? inpGetPedal();
// ? inpGetPortamento();
// ? inpGetPreAuxA();
// ? inpGetReverb();
// ? inpGetPreAuxB();
// ? inpGetPostAuxB();
// ? inpGetTremolo();
// ? inpGetAuxA();
// ? inpGetAuxB();
// ? inpInit();
// ? inpTranslateExCtrl();
// ? func_800FF248();
// ? func_800FF250();
// ? func_800FF258();
// ? func_800FF260();
// ? func_800FF268();
// ? func_800FF270();
// ? func_800FF278();
// ? func_800FF280();
// ? inpGetExCtrl();
// ? inpSetExCtrl();
// ? sndRand();
// ? sndSin();
// ? sndBSearch();
// ? sndConvertMs();
// ? sndConvertTicks();
// ? sndConvert2Ms();
// ? snd_handle_irq();
// ? hwInit();
// ? hwSetTimeOffset();
// ? hwGetTimeOffset();
// ? hwIsActive();
// ? hwSetMesgCallback();
// ? hwSetPriority();
// ? hwInitSamplePlayback();
// ? hwRelease();
// ? hwBreak();
// ? hwSetADSR();
// ? hwSetStreamLoopPS();
// ? hwStart();
// ? hwKeyOff();
// ? hwSetPitch();
// ? hwSetSRCType();
// ? hwSetPolyPhaseFilter();
// ? hwSetITDMode();
// ? hwSetVolume();
// ? hwOff();
// ? hwSetAUXProcessingCallbacks();
// ? hwActivateStudio();
// ? hwDeactivateStudio();
// ? hwAddInput();
// ? hwRemoveInput();
// ? hwGetPos();
// ? hwFlushStream();
// ? hwInitStream();
// ? hwExitStream();
// ? hwGetStreamPlayBuffer();
// ? hwTransAddr();
// ? hwFrq2Pitch();
// ? hwInitSampleMem();
// ? hwSaveSample();
// ? hwRemoveSample();
// ? hwSyncSampleMem();
// ? hwFrameDone();
// ? sndSetHooks();
// ? hwDisableHRTF();
// ? aramQueueCallback();
// ? aramUploadData();
// ? aramSyncTransferQueue();
// ? aramInit();
// ? aramGetZeroBuffer();
// ? aramStoreData();
// ? aramRemoveData();
// ? InitStreamBuffers();
// ? aramAllocateStreamBuffer();
// ? aramGetStreamBufferAddress();
// ? aramFreeStreamBuffer();
// ? salCallback();
// ? dspInitCallback();
// ? dspResumeCallback();
// ? salInitAi();
// ? salStartAi();
// ? salAiGetDest();
// ? salInitDsp();
// ? salCtrlDsp();
// ? salGetStartDelay();
// ? hwInitIrq();
// ? hwEnableIrq();
// ? hwDisableIrq();
// ? hwIRQEnterCritical();
// ? hwIRQLeaveCritical();
// ? salMalloc();
// ? salFree();
// ? sndAuxCallbackReverbHI();
// ? sndAuxCallbackPrepareReverbHI();
// ? ReverbHICreate();
// ? DoCrossTalk();
// ? HandleReverb();
// ? ReverbHICallback();
// ? do_src1();
// ? do_src2();
// ? sndAuxCallbackChorus();
// ? sndAuxCallbackPrepareChorus();
// ? __DTKCallbackForStreamStatus();
// ? __DTKCallbackForRun();
// ? __DTKCallbackForPreparePaused();
// ? __DTKCallbackForPlaylist();
// ? __DTKCallbackForAIInterrupt();
// ? __DTKCallbackForStop();
// ? __DTKCallbackForNextTrack();
// ? __DTKCallbackForPrevTrack();
// ? DTKInit();
// ? DTKQueueTrack();
// ? DTKRemoveTrack();
// ? DTKSetRepeatMode();
// ? DTKSetState();
// ? DTKNextTrack();
// ? DTKPrevTrack();
// ? DTKGetState();
// ? func_80103378();
// ? __va_arg();
// ? __destroy_global_chain();
// ? __unregister_fragment();
// ? __register_fragment();
// ? __cvt_fp2unsigned();
// ? __div2u();
// ? __div2i();
// ? __mod2u();
// ? __mod2i();
// ? __shl2i();
// ? __shr2u();
// ? __shr2i();
// ? __cvt_sll_flt();
// ? __cvt_dbl_usll();
// ? GetR2__Fv();
// ? exit();
// ? __num2dec();
// ? __flush_buffer();
// ? __prep_buffer();
// ? puts();
// ? __put_char();
// ? __kill_critical_regions();
// ? tolower();
// ? fwrite();
// ? wcstombs();
// ? memcmp();
// ? memchr();
// ? memmove();
// ? __copy_longs_rev_unaligned();
// ? __copy_longs_unaligned();
// ? __copy_longs_rev_aligned();
// ? __copy_longs_aligned();
// ? __stdio_atexit();
// ? sprintf();
// ? vsprintf();
// ? vprintf();
// ? printf();
// ? __StringWrite();
// ? __FileWrite();
// ? __pformatter();
// ? float2str();
// ? round_decimal();
// ? longlong2str();
// ? long2str();
// ? parse_format();
// ? srand();
// ? rand();
// ? strchr();
// ? strncmp();
// ? strcmp();
// ? strncat();
// ? strncpy();
// ? strcpy();
// ? strlen();
// ? func_80106B80();
// ? func_80106B88();
// ? func_80106C20();
// ? fwide();
// ? fabs__Fd();
// ? scalbn();
// ? __ieee754_rem_pio2();
// ? __fpclassifyd__Fd();
// ? __kernel_cos();
// ? __kernel_rem_pio2();
// ? __kernel_sin();
// ? copysign();
// ? cos();
// ? floor();
// ? frexp();
// ? ldexp();
// ? sin();
// ? fabsf__Ff();
// ? atanf();
// ? atan__Ff();
// ? _inv_sqrtf();
// ? acosf();
// ? tanf();
// ? cos__Ff();
// ? sin__Ff();
// ? cosf();
// ? sinf();
// ? powf();
// ? TRKHandleRequestEvent();
// ? TRKHandleSupportEvent();
// ? TRKIdle();
// ? TRKNubMainLoop();
// ? TRKInitializeEventQueue();
// ? TRKCopyEvent();
// ? TRKGetNextEvent();
// ? TRKPostEvent();
// ? TRKConstructEvent();
// ? TRKDestructEvent();
// ? TRKInitializeNub();
// ? TRKTerminateNub();
// ? TRKNubWelcome();
// ? TRKInitializeEndian();
// ? TRKMessageSend();
// ? TRKSetBufferUsed();
// ? TRKInitializeMessageBuffers();
// ? TRKGetFreeBuffer();
// ? TRKGetBuffer();
// ? TRKReleaseBuffer();
// ? TRKResetBuffer();
// ? TRKSetBufferPosition();
// ? TRKAppendBuffer();
// ? TRKReadBuffer();
// ? TRKAppendBuffer1_ui16();
// ? TRKAppendBuffer1_ui32();
// ? TRKAppendBuffer1_ui64();
// ? TRKAppendBuffer_ui8();
// ? TRKAppendBuffer_ui32();
// ? TRKReadBuffer1_ui8();
// ? TRKReadBuffer1_ui16();
// ? TRKReadBuffer1_ui32();
// ? TRKReadBuffer1_ui64();
// ? TRKReadBuffer_ui8();
// ? TRKReadBuffer_ui32();
// ? TRKTestForPacket();
// ? TRKGetInput();
// ? TRKProcessInput();
// ? TRKInitializeSerialHandler();
// ? TRKTerminateSerialHandler();
// ? usr_put_initialize();
// ? TRKInitializeDispatcher();
// ? TRKDispatchMessage();
// ? TRKMessageIntoReply();
// ? TRKSendACK();
// ? TRKStandardACK();
// ? TRKDoUnsupported();
// ? TRKDoConnect();
// ? TRKDoDisconnect();
// ? TRKDoReset();
// ? TRKDoVersions();
// ? TRKDoSupportmedia();
// ? TRKDoCPUType();
// ? TRKDoReadMemory();
// ? TRKDoWriteMemory();
// ? TRKDoReadRegisters();
// ? TRKDoWriteRegisters();
// ? TRKDoFlushCache();
// ? TRKDoContinue();
// ? TRKDoStep();
// ? TRKDoStop();
// ? TRKSuppAccessFile();
// ? TRKRequestSend();
// ? TRKInitializeMutex();
// ? TRKAcquireMutex();
// ? TRKReleaseMutex();
// ? TRKDoNotifyStopped();
// ? TRK_flush_cache();
// ? TRK_fill_mem();
// ? __TRK_get_MSR();
// ? __TRK_set_MSR();
// ? TRKValidMemory32();
// ? TRK_ppc_memcpy();
// ? TRKTargetAccessMemory();
// ? TRKTargetReadInstruction();
// ? TRKTargetAccessDefault();
// ? TRKTargetAccessFP();
// ? TRKTargetAccessExtended1();
// ? TRKTargetAccessExtended2();
// ? TRKTargetVersions();
// ? TRKTargetSupportMask();
// ? TRKTargetCPUType();
// ? TRKPostInterruptEvent();
// ? TRKSwapAndGo();
// ? TRKTargetInterrupt();
// ? TRKTargetAddStopInfo();
// ? TRKTargetAddExceptionInfo();
// ? TRKTargetEnableTrace();
// ? TRKTargetStepDone();
// ? TRKTargetDoStep();
// ? TRKTargetCheckStep();
// ? TRKTargetSingleStep();
// ? TRKTargetStepOutOfRange();
// ? TRKTargetGetPC();
// ? TRKTargetSupportRequest();
// ? TRKTargetFlushCache();
// ? TRKTargetStopped();
// ? TRKTargetSetStopped();
// ? TRKTargetStop();
// ? TRKPPCAccessSPR();
// ? TRKPPCAccessPairedSingleRegister();
// ? TRKPPCAccessFPRegister();
// ? TRKPPCAccessSpecialReg();
// ? TRKTargetSetInputPendingPtr();
// ? InitMetroTRK();
// ? EnableMetroTRKInterrupts();
// ? TRKTargetTranslate();
// ? TRK_copy_vector();
// ? __TRK_copy_vectors();
// ? TRKInitializeTarget();
// ? TRKSaveExtended1Block();
// ? TRKRestoreExtended1Block();
// ? TRKTargetCPUMinorType();
// ? TRK_main();
// ? TRKLoadContext();
// ? TRKEXICallBack();
// ? InitMetroTRKCommTable();
// ? TRKUARTInterruptHandler();
// ? TRKInitializeIntDrivenUART();
// ? EnableEXI2Interrupts();
// ? TRKPollUART();
// ? TRKReadUARTN();
// ? TRKWriteUARTN();
// ? ReserveEXI2Port();
// ? UnreserveEXI2Port();
// ? TRK_board_display();
// ? TRKTargetContinue();
// ? AmcEXIImm();
// ? AmcEXISync();
// ? AmcEXIClearInterrupts();
// ? AmcEXISetExiCallback();
// ? AmcEXISelect();
// ? AmcEXIDeselect();
// ? AmcDebugIntHandler();
// ? AmcEXIEnableInterrupts();
// ? AmcEXIInit();
// ? EXI2_CallBack();
// ? EXI2_Init();
// ? EXI2_EnableInterrupts();
// ? EXI2_Poll();
// ? EXI2_ReadN();
// ? EXI2_WriteN();
// ? EXI2_Reserve();
// ? EXI2_Unreserve();
// ? DBGEXIImm();
// ? DBGReadMailbox();
// ? DBGRead();
// ? DBGWrite();
// ? DBGReadStatus();
// ? MWCallback();
// ? DBGHandler();
// ? DBInitComm();
// ? DBInitInterrupts();
// ? DBQueryData();
// ? DBRead();
// ? DBWrite();
// ? DBOpen();
// ? DBClose();
// ? AMC_IsStub();
// ? Hu_IsStub();

#endif
